#!/usr/bin/env bash
set -u

SYSTEM="$(nix eval --impure --raw --expr builtins.currentSystem)"
MODE=""
for arg in "$@"; do
	case "$arg" in
		--test) MODE="test" ;;
		--debug) MODE="debug" ;;
	esac
done

case "$MODE" in
	test)
		exec nix build ".#checks.${SYSTEM}.test"
		;;
	debug)
		OUT_PATH="$(nix build --no-link --print-out-paths ".#packages.${SYSTEM}.debug")"
		;;
	*)
		OUT_PATH="$(nix build --no-link --print-out-paths ".#packages.${SYSTEM}.default")"
		;;
esac

if [ -e zig-out ] || [ -L zig-out ]; then
	mv zig-out "${HOME}/.Trash/libjxlz-zig-out.$(date +%s)"
fi

ln -s "${OUT_PATH}" zig-out
echo "built to ${OUT_PATH}"
