//! VarDCT strategy geometry and natural coefficient order.

const std = @import("std");
const JxlError = @import("../base/status.zig").JxlError;
pub const kNumValidStrategies = 27;

pub const Extent = struct { x: usize, y: usize };

/// Raw AC strategy dimensions in 8x8 blocks, including rectangular and
/// DCT128/256 strategies. Parsing geometry does not compute dequant tables.
pub fn strategyExtent(raw: i32) JxlError!Extent {
	const widths = [kNumValidStrategies]u8{ 1, 1, 1, 1, 2, 4, 1, 2, 1, 4, 2, 4, 1, 1, 1, 1, 1, 1, 8, 4, 8, 16, 8, 16, 32, 16, 32 };
	const heights = [kNumValidStrategies]u8{ 1, 1, 1, 1, 2, 4, 2, 1, 4, 1, 4, 2, 1, 1, 1, 1, 1, 1, 8, 8, 4, 16, 16, 8, 32, 32, 16 };
	if (raw < 0 or raw >= widths.len) return error.GenericError;
	const index: usize = @intCast(raw);
	return .{ .x = widths[index], .y = heights[index] };
}

/// Generalize zigzag scanning to rectangular DCTs, reserving the LLF prefix
/// for DC coefficients. Coefficient storage always has rows <= columns.
/// Complexity: O(order.len); the largest permitted aspect ratio is four.
pub fn naturalOrder(raw: i32, order: []u32) JxlError!void {
	const extent = try strategyExtent(raw);
	const cx = @max(extent.x, extent.y);
	const cy = @min(extent.x, extent.y);
	if (order.len != 64 * cx * cy) return error.GenericError;
	const ratio = cx / cy;
	const side = cx * 8;
	var cur = cx * cy;
	for (0..side) |i| {
		for (0..i + 1) |j| {
			const x = if (i % 2 == 0) j else i - j;
			const square_y = if (i % 2 == 0) i - j else j;
			if (square_y % ratio != 0) continue;
			const y = square_y / ratio;
			const index = if (x < cx and y < cy) y * cx + x else blk: {
				const index = cur;
				cur += 1;
				break :blk index;
			};
			order[index] = @intCast(y * side + x);
		}
	}
	var ip = side - 1;
	while (ip > 0) : (ip -= 1) {
		const i = ip - 1;
		for (0..i + 1) |j| {
			const x = side - 1 - (if (i % 2 == 0) i - j else j);
			const square_y = side - 1 - (if (i % 2 == 0) j else i - j);
			if (square_y % ratio != 0) continue;
			order[cur] = @intCast((square_y / ratio) * side + x);
			cur += 1;
		}
	}
}

const testing = std.testing;

test "natural coefficient orders match compiled upstream C++ for all strategies" {
	// Generated by tests/unit/coeff_order_oracle.cc against lib/jxl/ac_strategy.cc.
	// FNV-1a folds u32 coefficient indices as integers, independent of host endian.
	const sizes = [_]usize{ 64, 64, 64, 64, 256, 1024, 128, 128, 256, 256, 512, 512, 64, 64, 64, 64, 64, 64, 4096, 2048, 2048, 16384, 8192, 8192, 65536, 32768, 32768 };
	const hashes = [_]u64{
		0xdf110b46025d0e1d, 0xdf110b46025d0e1d, 0xdf110b46025d0e1d, 0xdf110b46025d0e1d,
		0x7887857312aa8f87, 0xd3b86541c7c3cf3b, 0x260e5f6564cdb74d, 0x260e5f6564cdb74d,
		0xaa4da9bdb3c00ef5, 0xaa4da9bdb3c00ef5, 0xa87ab1dfdb1b90eb, 0xa87ab1dfdb1b90eb,
		0xdf110b46025d0e1d, 0xdf110b46025d0e1d, 0xdf110b46025d0e1d, 0xdf110b46025d0e1d,
		0xdf110b46025d0e1d, 0xdf110b46025d0e1d, 0xde024e7cf7822fe9, 0xeff4ba5e55858ce9,
		0xeff4ba5e55858ce9, 0x149813ef5d4bf0ad, 0xca58cd74bfb956d5, 0xca58cd74bfb956d5,
		0x2698f82236172fb5, 0xa6943cd86c545665, 0xa6943cd86c545665,
	};
	for (sizes, hashes, 0..) |size, expected, raw| {
		const order = try testing.allocator.alloc(u32, size);
		defer testing.allocator.free(order);
		try naturalOrder(@intCast(raw), order);
		var hash: u64 = 14695981039346656037;
		for (order) |index| hash = (hash ^ index) *% 1099511628211;
		try testing.expectEqual(expected, hash);
	}
}

test "natural coefficient order rejects invalid strategy and output size" {
	var out: [64]u32 = undefined;
	try testing.expectError(error.GenericError, naturalOrder(-1, &out));
	try testing.expectError(error.GenericError, naturalOrder(27, &out));
	try testing.expectError(error.GenericError, naturalOrder(0, out[0..63]));
	try testing.expectError(error.GenericError, naturalOrder(4, &out));
}
