// AC-global metadata produced by retained upstream encoders.
#include <algorithm>
#include <cstdio>
#include <vector>
#include "lib/jxl/coeff_order.h"
#include "lib/jxl/enc_coeff_order.h"
#include "lib/jxl/enc_quant_weights.h"
#include "lib/jxl/enc_ans.h"
#include "lib/jxl/enc_aux_out.h"
#include "lib/jxl/field_encodings.h"
#include "lib/jxl/frame_header.h"
#include "lib/jxl/quant_weights.h"
#include "lib/jxl/memory_manager_internal.h"

jxl::Status Generate(JxlMemoryManager* memory) {
	jxl::BitWriter writer(memory);
	jxl::DequantMatrices matrices;
	JXL_RETURN_IF_ERROR(jxl::DequantMatricesEncode(memory, matrices, &writer, jxl::LayerType::Ac, nullptr));
	JXL_RETURN_IF_ERROR(writer.WithMaxBits(3, jxl::LayerType::Ac, nullptr, [&]() -> jxl::Status { writer.Write(3, 2); return true; }));
	std::vector<jxl::coeff_order_t> orders(jxl::kCoeffOrderMaxSize);
	for (unsigned raw = 0; raw < 27; ++raw) {
		const auto strategy = jxl::AcStrategy::FromRawStrategy(raw);
		for (size_t c = 0; c < 3; ++c) strategy.ComputeNaturalCoeffOrder(&orders[jxl::kCoeffOrderOffset[3*jxl::kStrategyOrder[raw]+c]*64]);
	}
	printf("// Generated by tests/unit/ac_global_oracle.cc with upstream encoders.\n");
	for (size_t pass = 0; pass < 2; ++pass) {
		const unsigned mask = pass == 0 ? 0 : 1;
		JXL_RETURN_IF_ERROR(writer.WithMaxBits(15, jxl::LayerType::Ac, nullptr, [&] { return jxl::U32Coder::Write(jxl::kOrderEnc, mask, &writer); }));
		if (pass == 1) for (size_t c = 0; c < 3; ++c) std::swap(orders[c*64+1], orders[c*64+2+c]);
		JXL_RETURN_IF_ERROR(jxl::EncodeCoeffOrders(mask, orders.data(), &writer, jxl::LayerType::Ac, nullptr));
		std::vector<std::vector<jxl::Token>> tokens(1);
		for (size_t i = 0; i < 128; ++i) tokens[0].emplace_back((i*97)%(3*7425), (i*19+pass)%61);
		jxl::HistogramParams params;
		params.lz77_method = jxl::HistogramParams::LZ77Method::kNone;
		params.force_huffman = pass == 1;
		jxl::EntropyEncodingData code;
		JXL_ASSIGN_OR_RETURN(size_t cost, jxl::BuildAndEncodeHistograms(memory, params, 3*7425, tokens, &code, &writer, jxl::LayerType::Ac, nullptr));
		(void)cost;
		jxl::BitWriter payload(memory);
		JXL_RETURN_IF_ERROR(jxl::WriteTokens(tokens[0], code, 0, &payload, jxl::LayerType::Ac, nullptr));
		printf("pub const payload_bits_%zu: usize = %zu;\npub const payload_%zu = [_]u8{",pass,payload.BitsWritten(),pass);
		payload.ZeroPadToByte();
		for (auto byte:payload.GetSpan()) printf("0x%02x,",byte);
		printf("};\n");
	}
	printf("pub const bits: usize = %zu;\npub const bytes = [_]u8{",writer.BitsWritten());
	writer.ZeroPadToByte();
	for(auto byte:writer.GetSpan()) printf("0x%02x,",byte);
	printf("};\n");
	return true;
}
int main() { JxlMemoryManager memory; if(!jxl::MemoryManagerInit(&memory,nullptr))return 1; return Generate(&memory)?0:2; }
