#include <jxl/decode.h>
#include <jxl/encode.h>
#include <jxl/color_encoding.h>
#include <cstdio>
#include <cstring>
#include <vector>
#include "lib/jxl/dec_bit_reader.h"
#include "lib/jxl/enc_fields.h"
#include "lib/jxl/enc_aux_out.h"
#include "lib/jxl/image_metadata.h"
#include "lib/jxl/memory_manager_internal.h"

#define CHECK(expr) do { if (!(expr)) { fprintf(stderr, "alpha oracle failed at line %d\n", __LINE__); return 1; } } while (0)

static bool with_preview(std::vector<unsigned char>& bytes) {
	if (bytes.size() < 2) return false;
	if (bytes[0] != 0xff || bytes[1] != 0x0a) {
		for (size_t offset = 0; bytes.size() - offset >= 8;) {
			const size_t size = (size_t(bytes[offset]) << 24) | (size_t(bytes[offset + 1]) << 16) | (size_t(bytes[offset + 2]) << 8) | bytes[offset + 3];
			if (size < 8 || size > bytes.size() - offset) return false;
			if (std::memcmp(bytes.data() + offset + 4, "jxlc", 4) == 0) {
				std::vector<unsigned char> stream(bytes.begin() + offset + 8, bytes.begin() + offset + size);
				if (!with_preview(stream) || stream.size() > UINT32_MAX - 8) return false;
				const uint32_t new_size = uint32_t(stream.size() + 8);
				for (unsigned i = 0; i < 4; ++i) bytes[offset + i] = uint8_t(new_size >> ((3 - i) * 8));
				bytes.erase(bytes.begin() + offset + 8, bytes.begin() + offset + size);
				bytes.insert(bytes.begin() + offset + 8, stream.begin(), stream.end());
				return true;
			}
			offset += size;
		}
		return false;
	}
	JxlMemoryManager memory;
	if (!jxl::MemoryManagerInit(&memory, nullptr)) return false;
	jxl::BitReader reader(bytes);
	if (reader.ReadBits(16) != 0x0aff) { (void)reader.Close(); return false; }
	jxl::CodecMetadata metadata;
	if (!jxl::ReadSizeHeader(&reader, &metadata.size) || !jxl::ReadImageMetadata(&reader, &metadata.m)) { (void)reader.Close(); return false; }
	metadata.transform_data.nonserialized_xyb_encoded = metadata.m.xyb_encoded;
	if (!jxl::Bundle::Read(&reader, &metadata.transform_data) || !reader.JumpToByteBoundary()) { (void)reader.Close(); return false; }
	const size_t offset = reader.TotalBitsConsumed() / 8;
	if (!reader.Close()) return false;
	metadata.m.have_preview = true;
	if (!metadata.m.preview_size.Set(3, 2)) return false;
	jxl::BitWriter writer(&memory);
	if (!jxl::WriteCodestreamHeaders(&metadata, &writer, nullptr)) return false;
	writer.ZeroPadToByte();
	auto header = writer.GetSpan();
	std::vector<unsigned char> result(header.begin(), header.end());
	result.insert(result.end(), bytes.begin() + offset, bytes.end());
	result.insert(result.end(), bytes.begin() + offset, bytes.end());
	bytes.swap(result);
	return true;
}

int main(int argc, char** argv) {
	const bool gray = argc > 1 && std::strcmp(argv[1], "gray") == 0;
	const bool preview = argc > 3;
	const unsigned char pixels8[] = { 0,0,0,0, 10,20,30,0, 16,32,64,64, 10,20,30,128, 64,128,255,255, 1,2,3,1 };
	const uint16_t pixels16[] = { 0,0,0,0, 16,32,64,0, 16384,32768,65535,65535, 1000,2000,4000,32768, 1,2,3,256, 1,2,3,1 };
	std::vector<unsigned char> gray8;
	std::vector<uint16_t> gray16;
	for (unsigned pixel = 0; pixel < 6; ++pixel) {
		gray8.push_back(pixels8[pixel * 4]); gray8.push_back(pixels8[pixel * 4 + 3]);
		gray16.push_back(pixels16[pixel * 4]); gray16.push_back(pixels16[pixel * 4 + 3]);
	}
	printf("// Generated by tests/unit/alpha_output_oracle.cc against upstream libjxl.\n");
	for (unsigned bits : {8u, 16u}) for (unsigned associated = 0; associated <= 1; ++associated) {
		auto *encoder = JxlEncoderCreate(nullptr);
		CHECK(encoder);
		JxlBasicInfo info;
		JxlEncoderInitBasicInfo(&info);
		info.xsize = 3; info.ysize = 2;
		if (argc > 2 && std::strcmp(argv[2], "rotate") == 0) info.orientation = JXL_ORIENT_ROTATE_90_CW;
		info.bits_per_sample = bits;
		info.num_color_channels = gray ? 1 : 3; info.num_extra_channels = 1;
		info.alpha_bits = bits; info.alpha_premultiplied = associated;
		info.uses_original_profile = JXL_TRUE;
		CHECK(JxlEncoderSetBasicInfo(encoder, &info) == JXL_ENC_SUCCESS);
		JxlColorEncoding color;
		JxlColorEncodingSetToSRGB(&color, gray ? JXL_TRUE : JXL_FALSE);
		CHECK(JxlEncoderSetColorEncoding(encoder, &color) == JXL_ENC_SUCCESS);
		auto *settings = JxlEncoderFrameSettingsCreate(encoder, nullptr);
		CHECK(JxlEncoderSetFrameLossless(settings, JXL_TRUE) == JXL_ENC_SUCCESS);
		const JxlPixelFormat input = {gray ? 2u : 4u, bits == 8 ? JXL_TYPE_UINT8 : JXL_TYPE_UINT16, JXL_NATIVE_ENDIAN, 0};
		const void* source = bits == 8 ? static_cast<const void*>(gray ? gray8.data() : pixels8) : static_cast<const void*>(gray ? gray16.data() : pixels16);
		CHECK(JxlEncoderAddImageFrame(settings, &input, source, 6 * input.num_channels * bits / 8) == JXL_ENC_SUCCESS);
		JxlEncoderCloseInput(encoder);
		std::vector<unsigned char> bytes(4096);
		unsigned char *next = bytes.data();
		size_t available = bytes.size();
		CHECK(JxlEncoderProcessOutput(encoder, &next, &available) == JXL_ENC_SUCCESS);
		bytes.resize(bytes.size() - available);
		JxlEncoderDestroy(encoder);
		if (preview) CHECK(with_preview(bytes));
		printf("pub const bytes_%u_%u = [_]u8{", bits, associated);
		for (auto byte : bytes) printf("%u,", byte);
		printf("};\n");
		for (unsigned unpremultiply = 0; unpremultiply <= 1; ++unpremultiply) {
			for (unsigned output_bits : {8u, 16u, 32u, 17u}) for (unsigned channels : {1u, 2u, 3u, 4u}) {
				if (!gray && channels < 3) continue;
				auto *decoder = JxlDecoderCreate(nullptr);
				CHECK(decoder);
				CHECK(JxlDecoderSetUnpremultiplyAlpha(decoder, unpremultiply) == JXL_DEC_SUCCESS);
				CHECK(JxlDecoderSubscribeEvents(decoder, JXL_DEC_BASIC_INFO | JXL_DEC_FULL_IMAGE | (preview ? JXL_DEC_PREVIEW_IMAGE : 0)) == JXL_DEC_SUCCESS);
				CHECK(JxlDecoderSetInput(decoder, bytes.data(), bytes.size()) == JXL_DEC_SUCCESS);
				JxlDecoderCloseInput(decoder);
				CHECK(JxlDecoderProcessInput(decoder) == JXL_DEC_BASIC_INFO);
				CHECK(JxlDecoderGetBasicInfo(decoder, &info) == JXL_DEC_SUCCESS);
				JxlExtraChannelInfo extra;
				CHECK(JxlDecoderGetExtraChannelInfo(decoder, 0, &extra) == JXL_DEC_SUCCESS);
				if (output_bits == 8 && channels == 3) printf("pub const info_%u_%u_%u = [_]i32{%d,%d};\n", bits, associated, unpremultiply, info.alpha_premultiplied, extra.alpha_premultiplied);
				const JxlPixelFormat output = {channels, output_bits == 8 ? JXL_TYPE_UINT8 : output_bits == 16 ? JXL_TYPE_UINT16 : output_bits == 32 ? JXL_TYPE_FLOAT : JXL_TYPE_FLOAT16, JXL_BIG_ENDIAN, 0};
				std::vector<unsigned char> preview_pixels;
				if (preview) {
					CHECK(JxlDecoderProcessInput(decoder) == JXL_DEC_NEED_PREVIEW_OUT_BUFFER);
					size_t preview_size = 0;
					CHECK(JxlDecoderPreviewOutBufferSize(decoder, &output, &preview_size) == JXL_DEC_SUCCESS);
					preview_pixels.resize(preview_size);
					CHECK(JxlDecoderSetPreviewOutBuffer(decoder, &output, preview_pixels.data(), preview_pixels.size()) == JXL_DEC_SUCCESS);
					CHECK(JxlDecoderProcessInput(decoder) == JXL_DEC_PREVIEW_IMAGE);
				}
				CHECK(JxlDecoderProcessInput(decoder) == JXL_DEC_NEED_IMAGE_OUT_BUFFER);
				size_t size = 0;
				CHECK(JxlDecoderImageOutBufferSize(decoder, &output, &size) == JXL_DEC_SUCCESS);
				std::vector<unsigned char> pixels(size);
				CHECK(JxlDecoderSetImageOutBuffer(decoder, &output, pixels.data(), pixels.size()) == JXL_DEC_SUCCESS);
				CHECK(JxlDecoderProcessInput(decoder) == JXL_DEC_FULL_IMAGE);
				CHECK(JxlDecoderProcessInput(decoder) == JXL_DEC_SUCCESS);
				if (preview) CHECK(pixels == preview_pixels);
				printf("pub const pixels_%u_%u_%u_%u_%u = [_]u8{", bits, associated, unpremultiply, output_bits, channels);
				for (auto byte : pixels) printf("%u,", byte);
				printf("};\n");
				JxlDecoderDestroy(decoder);
			}
		}
	}
}
