// Independent pixel oracle for JPEG XL patch and frame blending.
#include <cstdio>
#include <cmath>
#include <vector>
#include "lib/jxl/blending.h"
#include "lib/jxl/image.h"
#include "lib/jxl/memory_manager_internal.h"
jxl::Status Generate(JxlMemoryManager* memory,unsigned id){
 const unsigned mode=id%8,clamp=(id/8)%2,kind=id/16,extras=kind==0?0:kind==1?1:2,channels=3+extras,width=16;
 std::vector<jxl::ExtraChannelInfo> info(extras);
 for(unsigned i=0;i<extras;++i){info[i].type=kind==2&&i==0?jxl::ExtraChannel::kDepth:jxl::ExtraChannel::kAlpha;info[i].alpha_associated=kind==3&&i==0;}
 const unsigned alpha=kind==2?1:0;
 jxl::PatchBlending color{static_cast<jxl::PatchBlendMode>(mode),alpha,clamp!=0};
 std::vector<jxl::PatchBlending> extra(extras);for(unsigned i=0;i<extras;++i)extra[i]={static_cast<jxl::PatchBlendMode>((mode+i+1)%8),alpha,clamp!=0};
 JXL_ASSIGN_OR_RETURN(jxl::ImageF bg,jxl::ImageF::Create(memory,width,channels));
 JXL_ASSIGN_OR_RETURN(jxl::ImageF fg,jxl::ImageF::Create(memory,width,channels));
 JXL_ASSIGN_OR_RETURN(jxl::ImageF out,jxl::ImageF::Create(memory,width,channels));
 std::vector<const float*> bp(channels),fp(channels);std::vector<float*> op(channels);
 for(unsigned c=0;c<channels;++c){bp[c]=bg.Row(c);fp[c]=fg.Row(c);op[c]=out.Row(c);for(unsigned x=0;x<width;++x){bg.Row(c)[x]=float(int((x*13+c*5)%21)-5)/8;fg.Row(c)[x]=float(int((x*7+c*11)%23)-7)/8;if(x==0&&c>=3)bg.Row(c)[x]=fg.Row(c)[x]=0;}}
 JXL_RETURN_IF_ERROR(jxl::PerformBlending(memory,bp.data(),fp.data(),op.data(),0,width,color,extra.data(),info));
 auto emit=[&](const char* name,const jxl::ImageF& image,unsigned scale){printf("pub const %s_%u=[_]i32{",name,id);for(unsigned x=0;x<width;++x)for(unsigned c=0;c<channels;++c)printf("%d,",int(std::llround(image.ConstRow(c)[x]*scale)));printf("};\n");};
 emit("bg",bg,8);emit("fg",fg,8);emit("output",out,1<<20);return true;
}
int main(){JxlMemoryManager memory;if(!jxl::MemoryManagerInit(&memory,nullptr))return 1;printf("// Generated by tests/unit/blending_oracle.cc with libjxl v0.12.0. Inputs 2^3, output 2^20.\n");for(unsigned id=0;id<64;++id)if(!Generate(&memory,id))return 2;}
