// Transcode independently encoded JPEG samples, then decode with upstream.
#include <cstdio>
#include <vector>
#include "jxl/encode.h"
#include "jxl/decode.h"
#include "lib/jxl/fields.h"
#include "lib/jxl/frame_header.h"
#include "lib/jxl/memory_manager_internal.h"
#include "lib/jxl/enc_frame.h"
#include "lib/jxl/enc_fields.h"
#include "lib/jxl/enc_toc.h"
#include "lib/jxl/toc.h"
#include "lib/jxl/enc_aux_out.h"
bool BadSmoothing(const std::vector<unsigned char>& bytes,jxl::CodecMetadata* metadata,size_t start){
 JxlMemoryManager memory;if(!jxl::MemoryManagerInit(&memory,nullptr))return false;
 jxl::BitReader reader(jxl::Bytes(bytes.data()+start,bytes.size()-start));jxl::FrameHeader header(metadata);
 if(!jxl::ReadFrameHeader(&reader,&header)||header.chroma_subsampling.Is444())return false;
 std::vector<uint32_t> sizes;std::vector<jxl::coeff_order_t> permutation;
 if(!jxl::ReadToc(&memory,1,&reader,&sizes,&permutation)||!reader.JumpToByteBoundary())return false;
 const size_t payload=start+reader.TotalBitsConsumed()/8;if(!reader.Close()||payload+sizes[0]!=bytes.size())return false;
 jxl::BitWriter writer(&memory);if(!writer.WithMaxBits(start*8,jxl::LayerType::Header,nullptr,[&]{for(size_t i=0;i<start;++i)writer.Write(8,bytes[i]);return true;}))return false;
 std::vector<std::unique_ptr<jxl::BitWriter>> groups;groups.push_back(std::make_unique<jxl::BitWriter>(&memory));
 if(!groups[0]->WithMaxBits(sizes[0]*8,jxl::LayerType::ModularGlobal,nullptr,[&]{for(size_t i=payload;i<bytes.size();++i)groups[0]->Write(8,bytes[i]);return true;}))return false;
 header.flags &= ~jxl::FrameHeader::kSkipAdaptiveDCSmoothing;
 if(!jxl::WriteFrameHeader(header,&writer,nullptr)||!jxl::WriteGroupOffsets(groups,{},&writer,nullptr))return false;
 if(!writer.WithMaxBits(sizes[0]*8,jxl::LayerType::ModularGlobal,nullptr,[&]{for(size_t i=payload;i<bytes.size();++i)writer.Write(8,bytes[i]);return true;}))return false;
 auto result=writer.GetSpan();auto* dec=JxlDecoderCreate(nullptr);JxlDecoderSubscribeEvents(dec,JXL_DEC_FULL_IMAGE);JxlDecoderSetInput(dec,result.data(),result.size());JxlDecoderCloseInput(dec);const auto status=JxlDecoderProcessInput(dec);JxlDecoderDestroy(dec);if(status!=JXL_DEC_ERROR)return false;
 printf("pub const bad_smoothing=[_]u8{");for(auto b:result)printf("%u,",b);printf("};\n");return true;
}
bool Read(const char* path,std::vector<unsigned char>* bytes){FILE* file=fopen(path,"rb");if(!file)return false;if(fseek(file,0,SEEK_END))return false;long size=ftell(file);if(size<0||fseek(file,0,SEEK_SET))return false;bytes->resize(size);const bool ok=fread(bytes->data(),1,bytes->size(),file)==bytes->size();fclose(file);return ok;}
int main(int argc,char** argv){
 if(argc!=13)return 1;printf("// Generated by tests/unit/chroma_frame_oracle.cc with upstream libjxl.\n");
 for(unsigned id=0;id<12;++id){
  std::vector<unsigned char> jpeg;if(!Read(argv[id+1],&jpeg))return 2;
  auto* encoder=JxlEncoderCreate(nullptr);auto* settings=JxlEncoderFrameSettingsCreate(encoder,nullptr);
  if(JxlEncoderStoreJPEGMetadata(encoder,JXL_FALSE)!=JXL_ENC_SUCCESS||JxlEncoderAddJPEGFrame(settings,jpeg.data(),jpeg.size())!=JXL_ENC_SUCCESS)return 3;JxlEncoderCloseInput(encoder);
  std::vector<unsigned char> bytes(1<<20);auto* next=bytes.data();size_t avail=bytes.size();if(JxlEncoderProcessOutput(encoder,&next,&avail)!=JXL_ENC_SUCCESS)return 4;bytes.resize(bytes.size()-avail);JxlEncoderDestroy(encoder);
  if(bytes.size()<2||bytes[0]!=0xff||bytes[1]!=0x0a)return 5;
  jxl::CodecMetadata metadata;jxl::BitReader reader(jxl::Bytes(bytes.data()+2,bytes.size()-2));
  if(!jxl::ReadSizeHeader(&reader,&metadata.size)||!jxl::ReadImageMetadata(&reader,&metadata.m))return 6;
  metadata.transform_data.nonserialized_xyb_encoded=metadata.m.xyb_encoded;if(!jxl::Bundle::Read(&reader,&metadata.transform_data)||!reader.JumpToByteBoundary())return 7;
  const size_t start=2+reader.TotalBitsConsumed()/8;jxl::FrameHeader header(&metadata);if(!jxl::ReadFrameHeader(&reader,&header)||!reader.Close())return 8;
  if(id==1&&!BadSmoothing(bytes,&metadata,start))return 14;
  const unsigned hs[][3]={{0,0,0},{1,0,1},{1,0,1},{0,0,0},{0,1,0},{0,0,1}},vs[][3]={{0,0,0},{1,0,1},{0,0,0},{1,0,1},{0,1,0},{1,0,0}};
  for(unsigned c=0;c<3;++c)if(header.chroma_subsampling.HShift(c)!=hs[id%6][c]||header.chroma_subsampling.VShift(c)!=vs[id%6][c]){fprintf(stderr,"sampling mismatch id=%u c=%u\n",id,c);return 9;}
  if(header.encoding!=jxl::FrameEncoding::kVarDCT||header.color_transform!=jxl::ColorTransform::kYCbCr||metadata.m.color_encoding.WantICC())return 10;
  auto* decoder=JxlDecoderCreate(nullptr);JxlDecoderSubscribeEvents(decoder,JXL_DEC_FULL_IMAGE);JxlDecoderSetInput(decoder,bytes.data(),bytes.size());JxlDecoderCloseInput(decoder);
  JxlPixelFormat format={3,JXL_TYPE_UINT8,JXL_NATIVE_ENDIAN,0};std::vector<unsigned char> pixels(metadata.size.xsize()*metadata.size.ysize()*3);unsigned frames=0;
  for(;;){auto status=JxlDecoderProcessInput(decoder);if(status==JXL_DEC_SUCCESS)break;if(status==JXL_DEC_NEED_IMAGE_OUT_BUFFER){if(JxlDecoderSetImageOutBuffer(decoder,&format,pixels.data(),pixels.size())!=JXL_DEC_SUCCESS)return 11;}else if(status==JXL_DEC_FULL_IMAGE)++frames;else return 12;}
  JxlDecoderDestroy(decoder);if(frames!=1)return 13;
  printf("pub const bytes_%u=[_]u8{",id);for(auto byte:bytes)printf("%u,",byte);printf("};\npub const pixels_%u=[_]u8{",id);for(auto byte:pixels)printf("%u,",byte);printf("};\n");
 }
}
