// Gray XYB and embedded ICC output defaults, through upstream public decoding.
#include <cstdio>
#include <vector>
#include "jxl/encode.h"
#include "jxl/decode.h"
#include "jxl/color_encoding.h"
#include "lib/jxl/enc_fields.h"
#include "lib/jxl/enc_icc_codec.h"
#include "lib/jxl/enc_aux_out.h"
#include "lib/jxl/dec_bit_reader.h"
#include "lib/jxl/memory_manager_internal.h"
#include "lib/jxl/frame_header.h"
bool CheckFrame(const std::vector<unsigned char>& bytes,unsigned id){
 jxl::BitReader reader(bytes);if(reader.ReadBits(16)!=0x0aff)return false;jxl::CodecMetadata metadata;
 if(!jxl::ReadSizeHeader(&reader,&metadata.size)||!jxl::ReadImageMetadata(&reader,&metadata.m))return false;
 metadata.transform_data.nonserialized_xyb_encoded=metadata.m.xyb_encoded;
 if(!jxl::Bundle::Read(&reader,&metadata.transform_data)||!reader.JumpToByteBoundary())return false;
 jxl::FrameHeader frame(&metadata);if(!jxl::ReadFrameHeader(&reader,&frame)||!reader.Close())return false;
 if(frame.encoding!=(id%2?jxl::FrameEncoding::kModular:jxl::FrameEncoding::kVarDCT)||!frame.loop_filter.gab||frame.loop_filter.epf_iters!=id%4){fprintf(stderr,"frame mismatch id=%u mode=%u gab=%u epf=%u\n",id,unsigned(frame.encoding),unsigned(frame.loop_filter.gab),unsigned(frame.loop_filter.epf_iters));return false;}return true;
}
jxl::Status AddICC(std::vector<unsigned char>* bytes,bool gray){
 JxlMemoryManager memory;JXL_RETURN_IF_ERROR(jxl::MemoryManagerInit(&memory,nullptr));jxl::BitReader reader(*bytes);if(reader.ReadBits(16)!=0x0aff)return false;jxl::CodecMetadata metadata;
 JXL_RETURN_IF_ERROR(jxl::ReadSizeHeader(&reader,&metadata.size));JXL_RETURN_IF_ERROR(jxl::ReadImageMetadata(&reader,&metadata.m));metadata.transform_data.nonserialized_xyb_encoded=metadata.m.xyb_encoded;JXL_RETURN_IF_ERROR(jxl::Bundle::Read(&reader,&metadata.transform_data));JXL_RETURN_IF_ERROR(reader.JumpToByteBoundary());const size_t offset=reader.TotalBitsConsumed()/8;JXL_RETURN_IF_ERROR(reader.Close());
 auto icc=jxl::ColorEncoding::SRGB(gray).ICC();metadata.m.color_encoding.SetICCRaw(std::move(icc));
 jxl::BitWriter writer(&memory);JXL_RETURN_IF_ERROR(jxl::WriteCodestreamHeaders(&metadata,&writer,nullptr));JXL_RETURN_IF_ERROR(jxl::WriteICC(jxl::Bytes(metadata.m.color_encoding.ICC()),&writer,jxl::LayerType::Header,nullptr));writer.ZeroPadToByte();auto header=writer.GetSpan();std::vector<unsigned char> result(header.begin(),header.end());result.insert(result.end(),bytes->begin()+offset,bytes->end());*bytes=std::move(result);return true;
}
int main(){
 printf("// Generated by tests/unit/color_frame_oracle.cc.\n");
 for(unsigned id=0;id<16;++id){
  const bool gray=id<8||id>=12,alpha=id>=4&&id<8||id>=10;const unsigned colors=gray?1:3,channels=colors+alpha,width=19,height=13;
  auto* enc=JxlEncoderCreate(nullptr);JxlBasicInfo info;JxlEncoderInitBasicInfo(&info);info.xsize=width;info.ysize=height;info.num_color_channels=colors;info.bits_per_sample=8;info.uses_original_profile=JXL_FALSE;info.num_extra_channels=alpha;info.alpha_bits=alpha?8:0;if(JxlEncoderSetBasicInfo(enc,&info)!=JXL_ENC_SUCCESS)return 1;
  JxlColorEncoding color;if(id<8&&id%4>=2)JxlColorEncodingSetToLinearSRGB(&color,gray);else JxlColorEncodingSetToSRGB(&color,gray);if(JxlEncoderSetColorEncoding(enc,&color)!=JXL_ENC_SUCCESS)return 2;
  auto* settings=JxlEncoderFrameSettingsCreate(enc,nullptr);if(JxlEncoderSetFrameDistance(settings,1.f)!=JXL_ENC_SUCCESS||JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_MODULAR,id%2)!=JXL_ENC_SUCCESS||JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_EPF,id%4)!=JXL_ENC_SUCCESS||JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_GABORISH,1)!=JXL_ENC_SUCCESS||JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_PATCHES,0)!=JXL_ENC_SUCCESS||JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_NOISE,0)!=JXL_ENC_SUCCESS)return 3;
  std::vector<unsigned char> input(width*height*channels);for(unsigned y=0;y<height;++y)for(unsigned x=0;x<width;++x)for(unsigned c=0;c<channels;++c)input[(y*width+x)*channels+c]=(x*13+y*17+c*31)%256;
  JxlPixelFormat format={channels,JXL_TYPE_UINT8,JXL_NATIVE_ENDIAN,0};if(JxlEncoderAddImageFrame(settings,&format,input.data(),input.size())!=JXL_ENC_SUCCESS)return 4;JxlEncoderCloseInput(enc);std::vector<unsigned char> bytes(1<<20);auto* next=bytes.data();size_t avail=bytes.size();if(JxlEncoderProcessOutput(enc,&next,&avail)!=JXL_ENC_SUCCESS)return 5;bytes.resize(bytes.size()-avail);JxlEncoderDestroy(enc);if(!CheckFrame(bytes,id))return 13;if(id>=8&&!AddICC(&bytes,gray))return 6;
  auto* dec=JxlDecoderCreate(nullptr);JxlDecoderSubscribeEvents(dec,JXL_DEC_BASIC_INFO|JXL_DEC_COLOR_ENCODING|JXL_DEC_FULL_IMAGE);JxlDecoderSetInput(dec,bytes.data(),bytes.size());JxlDecoderCloseInput(dec);std::vector<unsigned char> output(input.size());unsigned frames=0;
  for(;;){auto status=JxlDecoderProcessInput(dec);if(status==JXL_DEC_SUCCESS)break;if(status==JXL_DEC_BASIC_INFO){JxlBasicInfo actual;if(JxlDecoderGetBasicInfo(dec,&actual)!=JXL_DEC_SUCCESS||actual.num_color_channels!=colors||actual.alpha_bits!=info.alpha_bits||actual.uses_original_profile)return 7;}
   else if(status==JXL_DEC_COLOR_ENCODING){JxlColorEncoding actual;auto original=JxlDecoderGetColorAsEncodedProfile(dec,JXL_COLOR_PROFILE_TARGET_ORIGINAL,&actual);if(original!=(id>=8?JXL_DEC_ERROR:JXL_DEC_SUCCESS))return 8;if(JxlDecoderGetColorAsEncodedProfile(dec,JXL_COLOR_PROFILE_TARGET_DATA,&actual)!=JXL_DEC_SUCCESS||actual.color_space!=(gray?JXL_COLOR_SPACE_GRAY:JXL_COLOR_SPACE_RGB)||actual.transfer_function!=(id>=8||id%4>=2?JXL_TRANSFER_FUNCTION_LINEAR:JXL_TRANSFER_FUNCTION_SRGB))return 9;}
   else if(status==JXL_DEC_NEED_IMAGE_OUT_BUFFER){if(JxlDecoderSetImageOutBuffer(dec,&format,output.data(),output.size())!=JXL_DEC_SUCCESS)return 10;}else if(status==JXL_DEC_FULL_IMAGE)++frames;else{fprintf(stderr,"id=%u status=%d\n",id,status);return 11;}}
  JxlDecoderDestroy(dec);if(frames!=1)return 12;printf("pub const bytes_%u=[_]u8{",id);for(auto b:bytes)printf("%u,",b);printf("};\npub const pixels_%u=[_]u8{",id);for(auto b:output)printf("%u,",b);printf("};\n");
 }
}
