// Upstream output matrices and public chromaticity coordinates.
#include <cstdio>
#include <cstring>
#include "jxl/color_encoding.h"
#include "jxl/encode.h"
#include "lib/jxl/dec_xyb.h"
int main(){
 printf("// Generated by tests/unit/color_matrix_oracle.cc.\n");
 const JxlPrimaries primaries[]={JXL_PRIMARIES_SRGB,JXL_PRIMARIES_P3,JXL_PRIMARIES_2100,JXL_PRIMARIES_CUSTOM};
 const JxlWhitePoint whites[]={JXL_WHITE_POINT_D65,JXL_WHITE_POINT_E,JXL_WHITE_POINT_DCI,JXL_WHITE_POINT_CUSTOM};
 for(unsigned id=0;id<40;++id){
  const bool gray=id>=32;const unsigned p=gray?0:id/8,w=(id/2)%4;
  JxlColorEncoding color;JxlColorEncodingSetToLinearSRGB(&color,gray);color.white_point=whites[w];color.primaries=primaries[p];
  color.white_point_xy[0]=0.321;color.white_point_xy[1]=0.345;
  color.primaries_red_xy[0]=0.67;color.primaries_red_xy[1]=0.33;
  color.primaries_green_xy[0]=0.21;color.primaries_green_xy[1]=0.71;
  color.primaries_blue_xy[0]=0.14;color.primaries_blue_xy[1]=0.08;
  jxl::CodecMetadata metadata;metadata.m.xyb_encoded=true;metadata.m.tone_mapping.intensity_target=id%2?1000:255;
  if(!metadata.m.color_encoding.FromExternal(color))return 1;
  if(id%2){metadata.transform_data.opsin_inverse_matrix.all_default=false;metadata.transform_data.opsin_inverse_matrix.inverse_matrix[0][0]*=0.97f;}
  printf("pub const source_%u=[_][3]u32{",id);for(auto& row:metadata.transform_data.opsin_inverse_matrix.inverse_matrix){printf(".{");for(float value:row){uint32_t bits;memcpy(&bits,&value,4);printf("0x%08x,",bits);}printf("},");}printf("};\n");
  jxl::OutputEncodingInfo info;if(!info.SetFromMetadata(metadata))return 2;
  printf("pub const matrix_%u=[_][3]u32{",id);for(unsigned r=0;r<3;++r){printf(".{");for(unsigned c=0;c<3;++c){uint32_t bits;memcpy(&bits,&info.opsin_params.inverse_opsin_matrix[(r*3+c)*4],4);printf("0x%08x,",bits);}printf("},");}printf("};\n");
  printf("pub const luminance_%u=[_]u32{",id);for(auto v:info.luminances){uint32_t bits;memcpy(&bits,&v,4);printf("0x%08x,",bits);}printf("};\n");
  auto original=metadata.m.color_encoding.ToExternal();auto output=info.color_encoding.ToExternal();
  for(unsigned t=0;t<2;++t){auto& c=t?output:original;printf("pub const %s_%u=[_]f64{",t?"data_xy":"original_xy",id);for(double v:c.white_point_xy)printf("%.17e,",v);for(double v:c.primaries_red_xy)printf("%.17e,",v);for(double v:c.primaries_green_xy)printf("%.17e,",v);for(double v:c.primaries_blue_xy)printf("%.17e,",v);printf("};\n");}
 }
}
