// Generates a Zig fixture with upstream's encoder and verifies it with its
// decoder. Link against a static retained-source libjxl build, as used by
// tests/cli/capi_compressed_icc_cross_oracle.sh.
#include <algorithm>
#include <cstdio>
#include <vector>
#include "lib/jxl/ac_strategy.h"
#include "lib/jxl/coeff_order.h"
#include "lib/jxl/dec_bit_reader.h"
#include "lib/jxl/enc_aux_out.h"
#include "lib/jxl/enc_bit_writer.h"
#include "lib/jxl/enc_coeff_order.h"
#include "lib/jxl/memory_manager_internal.h"

int main() {
	JxlMemoryManager memory;
	if (!jxl::MemoryManagerInit(&memory, nullptr)) return 1;
	std::vector<jxl::coeff_order_t> orders(jxl::kCoeffOrderMaxSize);
	unsigned computed = 0;
	for (unsigned raw = 0; raw < jxl::AcStrategy::kNumValidStrategies; ++raw) {
		const unsigned bucket = jxl::kStrategyOrder[raw];
		if (computed & (1u << bucket)) continue;
		computed |= 1u << bucket;
		const auto strategy = jxl::AcStrategy::FromRawStrategy(raw);
		const size_t llf = strategy.covered_blocks_x() * strategy.covered_blocks_y();
		for (size_t c = 0; c < 3; ++c) {
			auto* order = &orders[jxl::kCoeffOrderOffset[3 * bucket + c] * jxl::kDCTBlockSize];
			strategy.ComputeNaturalCoeffOrder(order);
			if (c == 0) std::swap(order[llf], order[llf + 1]);
			if (c == 1) std::reverse(order + llf, order + llf + 5);
			if (c == 2) std::rotate(order + llf, order + llf + 7, order + llf + 17);
		}
	}
	jxl::BitWriter writer(&memory);
	if (!jxl::EncodeCoeffOrders(0x1fff, orders.data(), &writer, jxl::LayerType::Header, nullptr)) return 2;
	const size_t bits = writer.BitsWritten();
	writer.ZeroPadToByte();
	const auto bytes = writer.GetSpan();
	std::vector<jxl::coeff_order_t> decoded(orders.size());
	jxl::BitReader reader(bytes);
	const bool ok = jxl::DecodeCoeffOrders(&memory, 0x1fff, (1u << 27) - 1, decoded.data(), &reader);
	const size_t consumed = reader.TotalBitsConsumed();
	if (!reader.Close() || !ok || decoded != orders || consumed != bits) return 3;
	printf("// Generated by tests/unit/custom_coeff_order_oracle.cc; upstream encode/decode agree.\n");
	printf("pub const encoded_bits: usize = %zu;\npub const bytes = [_]u8{\n", bits);
	for (size_t i = 0; i < bytes.size(); ++i) {
		printf("%s0x%02x,%s", i % 12 == 0 ? "\t" : " ", bytes[i], i % 12 == 11 ? "\n" : "");
	}
	printf("\n};\npub const hashes = [13][3]u64{\n");
	for (size_t bucket = 0; bucket < 13; ++bucket) {
		printf("\t.{");
		for (size_t c = 0; c < 3; ++c) {
			uint64_t hash = 14695981039346656037ull;
			const size_t begin = jxl::kCoeffOrderOffset[3 * bucket + c] * 64;
			const size_t end = jxl::kCoeffOrderOffset[3 * bucket + c + 1] * 64;
			for (size_t i = begin; i < end; ++i) hash = (hash ^ orders[i]) * 1099511628211ull;
			printf(" 0x%016llx,", (unsigned long long)hash);
		}
		printf(" },\n");
	}
	printf("};\n");
}
