// Generate full-plane DC smoothing expectations with retained upstream libjxl.
#include <cstdio>
#include "lib/jxl/compressed_dc.h"
#include "lib/jxl/memory_manager_internal.h"

void PrintImage(const char* label, size_t id, const jxl::Image3F& image, float scale) {
	printf("pub const %s_%zu = [_]i32{", label, id);
	for (size_t c = 0; c < 3; ++c)
		for (size_t y = 0; y < image.ysize(); ++y)
			for (size_t x = 0; x < image.xsize(); ++x)
				printf("%d,", static_cast<int>(image.ConstPlaneRow(c, y)[x] * scale));
	printf("};\n");
}

jxl::Status Generate(JxlMemoryManager* memory) {
	printf("// Generated by tests/unit/dc_smoothing_oracle.cc. Inputs scaled by 2^16, outputs by 2^24.\n");
	const float steps[] = {0.25f, 0.5f, 1.0f};
	for (size_t id = 0; id < 4; ++id) {
		const size_t width = id == 0 ? 2 : 5;
		const size_t height = 5;
		JXL_ASSIGN_OR_RETURN(jxl::Image3F image, jxl::Image3F::Create(memory, width, height));
		for (size_t c = 0; c < 3; ++c)
			for (size_t y = 0; y < height; ++y)
				for (size_t x = 0; x < width; ++x)
					image.PlaneRow(c, y)[x] = (static_cast<int>((c * 7 + x * 3 + y * 5) % 11) - 5) * steps[c] / 128;
		if (id >= 2) image.PlaneRow(0, 2)[2] += (id == 2 ? 128 : 20) * steps[0] / 32;
		PrintImage("input", id, image, 1 << 16);
		JXL_RETURN_IF_ERROR(jxl::AdaptiveDCSmoothing(memory, steps, &image, nullptr));
		PrintImage("output", id, image, 1 << 24);
	}
	return true;
}

int main() {
	JxlMemoryManager memory;
	if (!jxl::MemoryManagerInit(&memory, nullptr)) return 1;
	return Generate(&memory) ? 0 : 2;
}
