// Capture existing JPEG-transcode fixture pixels with upstream's public API.
#include <cstdio>
#include <vector>
#include "jxl/decode.h"
int main(int argc,char** argv){
 if(argc!=3)return 1;printf("// Generated by tests/unit/existing_chroma_oracle.cc.\n");
 for(unsigned id=0;id<2;++id){
  FILE* file=fopen(argv[id+1],"rb");if(!file)return 2;if(fseek(file,0,SEEK_END))return 3;long n=ftell(file);if(n<0||fseek(file,0,SEEK_SET))return 4;std::vector<unsigned char> data(n);if(fread(data.data(),1,data.size(),file)!=data.size())return 5;fclose(file);
  auto* dec=JxlDecoderCreate(nullptr);JxlDecoderSubscribeEvents(dec,JXL_DEC_BASIC_INFO|JXL_DEC_FULL_IMAGE);JxlDecoderSetInput(dec,data.data(),data.size());JxlDecoderCloseInput(dec);
  JxlPixelFormat format={3,JXL_TYPE_UINT8,JXL_NATIVE_ENDIAN,0};std::vector<unsigned char> pixels;unsigned frames=0;
  for(;;){const auto status=JxlDecoderProcessInput(dec);if(status==JXL_DEC_SUCCESS)break;
   if(status==JXL_DEC_BASIC_INFO){JxlBasicInfo info;if(JxlDecoderGetBasicInfo(dec,&info)!=JXL_DEC_SUCCESS)return 6;printf("pub const width_%u:usize=%u;\npub const height_%u:usize=%u;\n",id,info.xsize,id,info.ysize);}
   else if(status==JXL_DEC_NEED_IMAGE_OUT_BUFFER){size_t size;if(JxlDecoderImageOutBufferSize(dec,&format,&size)!=JXL_DEC_SUCCESS)return 7;pixels.resize(size);if(JxlDecoderSetImageOutBuffer(dec,&format,pixels.data(),pixels.size())!=JXL_DEC_SUCCESS)return 8;}
   else if(status==JXL_DEC_FULL_IMAGE)++frames;else return 9;
  }JxlDecoderDestroy(dec);if(frames!=1)return 10;
  printf("pub const pixels_%u=[_]u8{",id);for(auto b:pixels)printf("%u,",b);printf("};\n");
  if(id==1){printf("pub const bytes_1=[_]u8{");for(auto b:data)printf("%u,",b);printf("};\n");}
 }
}
