// Reference storage, cropped layers and all frame blend modes via libjxl.
#include <cstdio>
#include <vector>
#include "jxl/cms.h"
#include "jxl/decode.h"
#include "lib/jxl/enc_frame.h"
#include "lib/jxl/enc_fields.h"
#include "lib/jxl/memory_manager_internal.h"
jxl::Status Generate(JxlMemoryManager* memory,unsigned id){
 const unsigned width=13,height=9,extras=1+id/5,channels=3+extras;
 jxl::CodecMetadata metadata;JXL_RETURN_IF_ERROR(metadata.size.Set(width,height));metadata.m.SetUintSamples(8);metadata.m.xyb_encoded=false;metadata.m.color_encoding=jxl::ColorEncoding::SRGB();
 metadata.m.extra_channel_info.resize(extras);for(auto& extra:metadata.m.extra_channel_info){extra.type=jxl::ExtraChannel::kAlpha;extra.bit_depth.bits_per_sample=8;extra.alpha_associated=id%2;}
 jxl::BitWriter writer(memory);JXL_RETURN_IF_ERROR(jxl::WriteCodestreamHeaders(&metadata,&writer,nullptr));writer.ZeroPadToByte();
 jxl::CompressParams params;params.SetLossless();params.gaborish=jxl::Override::kOff;params.epf=0;params.patches=jxl::Override::kOff;params.speed_tier=jxl::SpeedTier::kThunder;JXL_RETURN_IF_ERROR(jxl::ParamsPostInit(&params));
 for(unsigned frame=0;frame<2;++frame){
  const unsigned w=width,h=height;
  jxl::ImageBundle bundle(memory,&metadata.m);
  JXL_ASSIGN_OR_RETURN(jxl::Image3F image,jxl::Image3F::Create(memory,w,h));
  for(unsigned c=0;c<3;++c)for(unsigned y=0;y<h;++y)for(unsigned x=0;x<w;++x)image.PlaneRow(c,y)[x]=((x*13+y*7+c*29+frame*17)%180)/255.f;
  JXL_RETURN_IF_ERROR(bundle.SetFromImage(std::move(image),metadata.m.color_encoding));
  std::vector<jxl::ImageF> ec;for(unsigned e=0;e<extras;++e){JXL_ASSIGN_OR_RETURN(jxl::ImageF plane,jxl::ImageF::Create(memory,w,h));for(unsigned y=0;y<h;++y)for(unsigned x=0;x<w;++x)plane.Row(y)[x]=((x*17+y*11+frame*31)%200)/255.f;ec.push_back(std::move(plane));}JXL_RETURN_IF_ERROR(bundle.SetExtraChannels(std::move(ec)));
  jxl::FrameInfo info;info.is_last=frame==1;info.save_as_reference=frame?0:1;info.source=1;info.blend=frame!=0;info.blendmode=static_cast<jxl::BlendMode>(id%5);info.clamp=id%2;info.alpha_channel=0;
  info.blendmode=jxl::BlendMode::kReplace;
  info.blend=frame!=0;
  info.extra_channel_blending_info.resize(extras);
  for(unsigned e=0;e<extras;++e){auto& blend=info.extra_channel_blending_info[e];blend.mode=frame?static_cast<jxl::BlendMode>((id+e)%5):jxl::BlendMode::kReplace;blend.source=frame?1:0;blend.alpha_channel=extras-1;blend.clamp=id%2;}
  bundle.origin=info.origin;bundle.blend=info.blend;bundle.blendmode=info.blendmode;
  const size_t frame_start=writer.BitsWritten()/8;
  if(!jxl::EncodeFrame(memory,params,info,&metadata,bundle,*JxlGetDefaultCms(),nullptr,&writer,nullptr)){fprintf(stderr,"encode failed id=%u frame=%u\n",id,frame);return false;}writer.ZeroPadToByte();
  auto span=writer.GetSpan();jxl::BitReader check(jxl::Bytes(span.data()+frame_start,span.size()-frame_start));jxl::FrameHeader actual(&metadata);JXL_RETURN_IF_ERROR(jxl::ReadFrameHeader(&check,&actual));JXL_RETURN_IF_ERROR(check.Close());
  if(actual.custom_size_or_origin||actual.blending_info.mode!=jxl::BlendMode::kReplace||actual.extra_channel_blending_info[0].mode!=(frame?static_cast<jxl::BlendMode>(id):jxl::BlendMode::kReplace)){fprintf(stderr,"extra-only fixture settings were not emitted\n");return false;}
 }
 auto data=writer.GetSpan();JxlDecoder* decoder=JxlDecoderCreate(nullptr);JxlDecoderSubscribeEvents(decoder,JXL_DEC_FULL_IMAGE);JxlDecoderSetInput(decoder,data.data(),data.size());JxlDecoderCloseInput(decoder);
 JxlPixelFormat format={channels,JXL_TYPE_UINT8,JXL_NATIVE_ENDIAN,0};std::vector<unsigned char> pixels(width*height*channels);unsigned frames=0;
 for(;;){const auto status=JxlDecoderProcessInput(decoder);if(status==JXL_DEC_SUCCESS)break;if(status==JXL_DEC_NEED_IMAGE_OUT_BUFFER){if(JxlDecoderSetImageOutBuffer(decoder,&format,pixels.data(),pixels.size())!=JXL_DEC_SUCCESS){fprintf(stderr,"set buffer failed\n");return false;}}else if(status==JXL_DEC_FULL_IMAGE)++frames;else {fprintf(stderr,"decode status=%d id=%u\n",status,id);return false;}}
 JxlDecoderDestroy(decoder);printf("pub const bytes_%u=[_]u8{",id);for(auto byte:data)printf("%u,",byte);printf("};\npub const frames_%u:usize=%u;\npub const pixels_%u=[_]u8{",id,frames,id);for(auto byte:pixels)printf("%u,",byte);printf("};\n");return true;
}
int main(){JxlMemoryManager memory;if(!jxl::MemoryManagerInit(&memory,nullptr))return 1;printf("// Generated by tests/unit/extra_blend_oracle.cc.\n");for(unsigned id=0;id<5;++id)if(!Generate(&memory,id))return 2;}
