// Finite floating-point color and alpha samples through upstream's public API.
#include <cstdio>
#include <cstring>
#include <vector>
#include "jxl/encode.h"
#include "jxl/decode.h"
#include "jxl/color_encoding.h"
#include "lib/jxl/fields.h"
#include "lib/jxl/frame_header.h"
#include "lib/jxl/memory_manager_internal.h"
unsigned Read32(const unsigned char* p){return (unsigned(p[0])<<24)|(unsigned(p[1])<<16)|(unsigned(p[2])<<8)|p[3];}
int main(){
 printf("// Generated by tests/unit/float_frame_oracle.cc.\n");
 const unsigned bits[]={16,24,32,11},exps[]={5,7,8,4};
 for(unsigned id=0;id<20;++id){
  const bool original=id<8||id>=16,modular=id<12||id>=16,gray=id==6||id==7;
  const unsigned width=id==0?1:id==19?257:13,height=id==0?1:id==19?17:9,colors=gray?1:3,extras=id%2||id>=16,channels=colors+extras,bpc=id>=16?8:bits[id%4],exp=id>=16?0:exps[id%4];
  JxlBasicInfo info;JxlEncoderInitBasicInfo(&info);info.xsize=width;info.ysize=height;info.bits_per_sample=bpc;info.exponent_bits_per_sample=exp;info.uses_original_profile=original;info.num_color_channels=colors;
  if(extras){info.num_extra_channels=1;info.alpha_bits=id==13||id==15?32:bits[(id+1)%4];info.alpha_exponent_bits=id==13||id==15?8:exps[(id+1)%4];}
  auto* enc=JxlEncoderCreate(nullptr);if(JxlEncoderSetBasicInfo(enc,&info)!=JXL_ENC_SUCCESS)return 1;
  JxlColorEncoding color;JxlColorEncodingSetToSRGB(&color,gray);if(JxlEncoderSetColorEncoding(enc,&color)!=JXL_ENC_SUCCESS)return 2;
  auto* settings=JxlEncoderFrameSettingsCreate(enc,nullptr);
  if(JxlEncoderSetFrameDistance(settings,original?0.f:1.f)!=JXL_ENC_SUCCESS||JxlEncoderSetFrameLossless(settings,original)!=JXL_ENC_SUCCESS)return 3;
  if(JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_MODULAR,modular)!=JXL_ENC_SUCCESS||JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_EFFORT,5)!=JXL_ENC_SUCCESS)return 4;
  for(auto setting:{JXL_ENC_FRAME_SETTING_NOISE,JXL_ENC_FRAME_SETTING_PATCHES,JXL_ENC_FRAME_SETTING_GABORISH,JXL_ENC_FRAME_SETTING_EPF})if(JxlEncoderFrameSettingsSetOption(settings,setting,0)!=JXL_ENC_SUCCESS)return 5;
  const unsigned sampling=id>=13&&id<=15?1u<<(id-12):1;
  if(sampling!=1&&(JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_RESAMPLING,sampling)!=JXL_ENC_SUCCESS||JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_EXTRA_CHANNEL_RESAMPLING,sampling)!=JXL_ENC_SUCCESS))return 21;
  std::vector<float> input(width*height*channels);
  for(unsigned y=0;y<height;++y)for(unsigned x=0;x<width;++x)for(unsigned c=0;c<channels;++c)input[(y*width+x)*channels+c]=(int(((x*13+y*17+c*29)%192)/4)-(original&&id<16?8:0))/32.f;
  JxlPixelFormat format={channels,JXL_TYPE_FLOAT,JXL_NATIVE_ENDIAN,0};if(JxlEncoderAddImageFrame(settings,&format,input.data(),input.size()*sizeof(float))!=JXL_ENC_SUCCESS)return 6;JxlEncoderCloseInput(enc);
  std::vector<unsigned char> bytes(1<<20);auto* next=bytes.data();size_t avail=bytes.size();if(JxlEncoderProcessOutput(enc,&next,&avail)!=JXL_ENC_SUCCESS)return 7;bytes.resize(bytes.size()-avail);JxlEncoderDestroy(enc);
  std::vector<unsigned char> codestream;
  if(bytes[0]==0xff&&bytes[1]==0x0a)codestream=bytes;
  else for(size_t offset=0;offset<bytes.size();){if(bytes.size()-offset<8)return 16;size_t size=Read32(bytes.data()+offset);if(size==0)size=bytes.size()-offset;if(size<8||size>bytes.size()-offset)return 17;const unsigned type=Read32(bytes.data()+offset+4);if(type==0x6a786c63)codestream.insert(codestream.end(),bytes.begin()+offset+8,bytes.begin()+offset+size);else if(type==0x6a786c70){if(size<12)return 18;codestream.insert(codestream.end(),bytes.begin()+offset+12,bytes.begin()+offset+size);}offset+=size;}
  if(codestream.size()<2||codestream[0]!=0xff||codestream[1]!=0x0a)return 19;
  jxl::CodecMetadata metadata;jxl::BitReader reader(jxl::Bytes(codestream.data()+2,codestream.size()-2));if(!jxl::ReadSizeHeader(&reader,&metadata.size)||!jxl::ReadImageMetadata(&reader,&metadata.m))return 8;
  metadata.transform_data.nonserialized_xyb_encoded=metadata.m.xyb_encoded;if(!jxl::Bundle::Read(&reader,&metadata.transform_data)||!reader.JumpToByteBoundary())return 9;
  jxl::FrameHeader actual(&metadata);if(!jxl::ReadFrameHeader(&reader,&actual)||!reader.Close())return 10;
  if(metadata.m.bit_depth.bits_per_sample!=bpc||metadata.m.bit_depth.exponent_bits_per_sample!=exp||metadata.m.bit_depth.floating_point_sample!=(exp!=0)||actual.encoding!=(modular?jxl::FrameEncoding::kModular:jxl::FrameEncoding::kVarDCT)||actual.upsampling!=sampling)return 11;
  if(extras){const auto& extra=metadata.m.extra_channel_info[0];if(!extra.bit_depth.floating_point_sample||extra.bit_depth.bits_per_sample!=info.alpha_bits||extra.bit_depth.exponent_bits_per_sample!=info.alpha_exponent_bits)return 12;}
  printf("pub const bytes_%u=[_]u8{",id);for(auto b:bytes)printf("%u,",b);printf("};\npub const codestream_%u=[_]u8{",id);for(auto b:codestream)printf("%u,",b);printf("};\n");
  for(unsigned kind=0;kind<(original?2u:3u);++kind){
   auto* dec=JxlDecoderCreate(nullptr);JxlDecoderSubscribeEvents(dec,JXL_DEC_FULL_IMAGE|(kind==2?JXL_DEC_COLOR_ENCODING:0));JxlDecoderSetInput(dec,bytes.data(),bytes.size());JxlDecoderCloseInput(dec);
   format.data_type=kind?JXL_TYPE_FLOAT:JXL_TYPE_UINT8;std::vector<unsigned char> output(width*height*channels*(kind?4:1));unsigned frames=0;
   for(;;){auto status=JxlDecoderProcessInput(dec);if(status==JXL_DEC_SUCCESS)break;if(status==JXL_DEC_NEED_IMAGE_OUT_BUFFER){if(JxlDecoderSetImageOutBuffer(dec,&format,output.data(),output.size())!=JXL_DEC_SUCCESS)return 13;}else if(status==JXL_DEC_FULL_IMAGE)++frames;else if(status==JXL_DEC_COLOR_ENCODING){JxlColorEncoding linear;JxlColorEncodingSetToLinearSRGB(&linear,gray);if(JxlDecoderSetPreferredColorProfile(dec,&linear)!=JXL_DEC_SUCCESS)return 20;}else return 14;}
   JxlDecoderDestroy(dec);if(frames!=1)return 15;
   printf("pub const %s_%u=[_]%s{",kind==2?"linear_bits":kind?"float_bits":"pixels",id,kind?"u32":"u8");
   if(kind){for(size_t i=0;i<output.size();i+=4){unsigned value;memcpy(&value,output.data()+i,4);printf("0x%08x,",value);}}else for(auto b:output)printf("%u,",b);printf("};\n");
  }
 }
}
