// Compare nonfinite samples with the actual upstream upsampling stage.
#include <cstdio>
#include <cstring>
#include "lib/jxl/image_ops.h"
#include "lib/jxl/memory_manager_internal.h"
#include "lib/jxl/image_metadata.h"
#include "lib/jxl/render_pipeline/stage_upsampling.h"
struct StageAccess: jxl::RenderPipelineStage {using jxl::RenderPipelineStage::PrepareForThreads;};
static unsigned Bits(float value) {unsigned bits;memcpy(&bits,&value,4);return bits;}
static jxl::Status Generate(JxlMemoryManager* memory,unsigned id){
 const size_t width=id==0?1:id==1?7:31,height=id==0?3:id==1?5:19,pad=jxl::kRenderPipelineXOffset;
 JXL_ASSIGN_OR_RETURN(jxl::ImageF input,jxl::ImageF::Create(memory,width+2*pad,height+4));
 for(size_t y=0;y<height+4;++y)for(size_t x=0;x<width+2*pad;++x){
  const size_t mx=jxl::Mirror(static_cast<int64_t>(x)-pad,width),my=jxl::Mirror(static_cast<int64_t>(y)-2,height);
  float value=(int((mx*13+my*17)%37)-18)/256.f;
  unsigned bits=Bits(value);
  if(mx==0&&my==0)bits=0x7f800000;
  if(mx==width-1&&my==height-1)bits=0xff800000;
  if(mx==width/2&&my==height/2)bits=0xffc12345;
  if(mx==width/3&&my==height/3)bits=0x80000000;
  memcpy(&input.Row(y)[x],&bits,4);
 }
 printf("pub const width_%u=%zu;\npub const height_%u=%zu;\npub const input_%u=[_]u32{",id,width,id,height,id);
 for(size_t y=0;y<height;++y)for(size_t x=0;x<width;++x)printf("0x%08x,",Bits(input.Row(y+2)[x+pad]));printf("};\n");
 for(size_t shift=1;shift<=3;++shift){const size_t factor=1<<shift;
  jxl::CustomTransformData params;
  if(id==3){float* weights=shift==1?params.upsampling2_weights:shift==2?params.upsampling4_weights:params.upsampling8_weights;const size_t count=shift==1?15:shift==2?55:210;for(size_t i=0;i<count;++i)weights[i]=(int(i%7)-3)/64.f;}
  auto stage=jxl::GetUpsamplingStage(memory,params,0,shift);JXL_RETURN_IF_ERROR((stage.get()->*&StageAccess::PrepareForThreads)(1));
  JXL_ASSIGN_OR_RETURN(jxl::ImageF output,jxl::ImageF::Create(memory,width*factor+2*pad,height*factor));
  for(size_t y=0;y<height;++y){jxl::RenderPipelineStage::RowInfo rows(1),out(1);for(size_t dy=0;dy<5;++dy)rows[0].push_back(input.Row(y+dy));for(size_t dy=0;dy<factor;++dy)out[0].push_back(output.Row(y*factor+dy));JXL_RETURN_IF_ERROR(stage->ProcessRow(rows,out,0,width,0,y,0));}
  printf("pub const output_%u_%zu=[_]u32{",id,factor);for(size_t y=0;y<height*factor;++y)for(size_t x=0;x<width*factor;++x)printf("0x%08x,",Bits(output.Row(y)[x+pad]));printf("};\n");
 }
 return true;
}
int main(){JxlMemoryManager memory;if(!jxl::MemoryManagerInit(&memory,nullptr))return 1;printf("// Generated by tests/unit/float_upsampling_oracle.cc.\n");for(unsigned id=0;id<4;++id)if(!Generate(&memory,id))return 2;}
