// Exact binary32 representation returned by upstream modular int_to_float.
#include <cstdint>
#include <cstring>
#include <cstdio>
#include "lib/jxl/base/status.h"
namespace jxl { Status int_to_float(const int32_t*,float*,size_t,int,int); }
int main(){
 printf("// Generated by tests/unit/float_sample_oracle.cc.\npub const cases=[_][4]u32{\n");
 uint32_t seed=0x195be764;
 for(unsigned exp=2;exp<=8;++exp)for(unsigned mant=2;mant<=23&&mant+exp+1<=32;++mant){
  const unsigned bits=mant+exp+1;const uint32_t fraction=(1u<<mant)-1,sign=1u<<(bits-1),special=((1u<<exp)-1)<<mant;
  const uint32_t edges[]={0,sign,1,sign|1,fraction,sign|fraction,1u<<mant,sign|(1u<<mant),special-1,sign|(special-1),special,sign|special,special|1,sign|special|1,0xffffffff};
  for(unsigned i=0;i<47;++i){seed^=seed<<13;seed^=seed>>17;seed^=seed<<5;const uint32_t wire=i<15?edges[i]:seed&((uint64_t(1)<<bits)-1);int32_t raw;memcpy(&raw,&wire,4);float value;if(!jxl::int_to_float(&raw,&value,1,bits,exp))return 1;uint32_t result;memcpy(&result,&value,4);printf(".{%u,%u,0x%08x,0x%08x},\n",bits,exp,wire,result);}
 }
 printf("};\n");
}
