// Legal color/extra sampling pairs with nonfinite alpha and integer/float color.
#include <cstdio>
#include <cstring>
#include <vector>
#include "jxl/cms.h"
#include "jxl/decode.h"
#include "lib/jxl/enc_frame.h"
#include "lib/jxl/enc_fields.h"
#include "lib/jxl/memory_manager_internal.h"
static jxl::Status Generate(JxlMemoryManager* memory,unsigned id){
 const unsigned color_factors[]={1,1,1,2,2,2,4,4,8},extra_factors[]={2,4,8,2,4,8,4,8,8};
 const unsigned factor=color_factors[id%9],extra_factor=extra_factors[id%9],width=13,height=9,out_width=width*factor-1,out_height=height*factor-1;
 jxl::CodecMetadata metadata;JXL_RETURN_IF_ERROR(metadata.size.Set(out_width,out_height));if(id>=9)metadata.m.SetFloat32Samples();else metadata.m.SetUintSamples(8);metadata.m.xyb_encoded=false;metadata.m.color_encoding=jxl::ColorEncoding::SRGB();
 metadata.m.extra_channel_info.resize(1);auto& alpha=metadata.m.extra_channel_info[0];alpha.type=jxl::ExtraChannel::kAlpha;alpha.bit_depth.bits_per_sample=32;alpha.bit_depth.floating_point_sample=true;alpha.bit_depth.exponent_bits_per_sample=8;
 jxl::BitWriter writer(memory);JXL_RETURN_IF_ERROR(jxl::WriteCodestreamHeaders(&metadata,&writer,nullptr));writer.ZeroPadToByte();const size_t start=writer.BitsWritten()/8;
 jxl::CompressParams params;params.SetLossless();params.resampling=factor;params.ec_resampling=extra_factor;params.already_downsampled=true;params.gaborish=jxl::Override::kOff;params.epf=0;params.patches=jxl::Override::kOff;params.speed_tier=jxl::SpeedTier::kThunder;JXL_RETURN_IF_ERROR(jxl::ParamsPostInit(&params));
 jxl::ImageBundle bundle(memory,&metadata.m);JXL_ASSIGN_OR_RETURN(jxl::Image3F image,jxl::Image3F::Create(memory,width,height));
 for(unsigned c=0;c<3;++c)for(unsigned y=0;y<height;++y)for(unsigned x=0;x<width;++x){
  float value=float((x*13+y*7+c*29)%200)/255.f;unsigned bits;memcpy(&bits,&value,4);
  if(id>=9&&x==0&&y==0)bits=0x7f800000;
  if(id>=9&&x==width-1&&y==height-1)bits=0xff800000;
  if(id>=9&&x==width/2&&y==height/2)bits=0x7fc12345;
  memcpy(&image.PlaneRow(c,y)[x],&bits,4);
 }
 JXL_RETURN_IF_ERROR(bundle.SetFromImage(std::move(image),metadata.m.color_encoding));
 JXL_ASSIGN_OR_RETURN(jxl::ImageF plane,jxl::ImageF::Create(memory,width,height));const unsigned words[]={0,0x80000000,0x7f800000,0xff800000,0x7fc12345,0xffc00001,1,0x7f7fffff,0x3f800000,0xbf800000};
 for(unsigned y=0;y<height;++y)for(unsigned x=0;x<width;++x){const unsigned bits=words[(x+3*y)%10];memcpy(&plane.Row(y)[x],&bits,4);}std::vector<jxl::ImageF> ec;ec.push_back(std::move(plane));JXL_RETURN_IF_ERROR(bundle.SetExtraChannels(std::move(ec)));
 jxl::FrameInfo info;info.is_last=true;JXL_RETURN_IF_ERROR(jxl::EncodeFrame(memory,params,info,&metadata,bundle,*JxlGetDefaultCms(),nullptr,&writer,nullptr));writer.ZeroPadToByte();
 auto bytes=writer.GetSpan();jxl::BitReader check(jxl::Bytes(bytes.data()+start,bytes.size()-start));jxl::FrameHeader actual(&metadata);JXL_RETURN_IF_ERROR(jxl::ReadFrameHeader(&check,&actual));JXL_RETURN_IF_ERROR(check.Close());
 if(actual.upsampling!=factor||actual.extra_channel_upsampling[0]!=extra_factor||actual.loop_filter.gab||actual.loop_filter.epf_iters||actual.encoding!=jxl::FrameEncoding::kModular)return false;
 auto* dec=JxlDecoderCreate(nullptr);JxlDecoderSubscribeEvents(dec,JXL_DEC_FULL_IMAGE);JxlDecoderSetInput(dec,bytes.data(),bytes.size());JxlDecoderCloseInput(dec);
 JxlPixelFormat format={4,JXL_TYPE_FLOAT,JXL_NATIVE_ENDIAN,0};std::vector<unsigned char> output(out_width*out_height*4*4);unsigned frames=0;
 for(;;){auto status=JxlDecoderProcessInput(dec);if(status==JXL_DEC_SUCCESS)break;if(status==JXL_DEC_NEED_IMAGE_OUT_BUFFER){size_t size=0;if(JxlDecoderImageOutBufferSize(dec,&format,&size)!=JXL_DEC_SUCCESS||size!=output.size())return false;if(JxlDecoderSetImageOutBuffer(dec,&format,output.data(),output.size())!=JXL_DEC_SUCCESS)return false;}else if(status==JXL_DEC_FULL_IMAGE)++frames;else{fprintf(stderr,"float extra upsampling id=%u status=%d\n",id,status);return false;}}
 JxlDecoderDestroy(dec);if(frames!=1)return false;
 printf("pub const bytes_%u=[_]u8{",id);for(auto b:bytes)printf("%u,",b);printf("};\npub const float_%u=[_]u32{",id);
 for(size_t i=0;i<output.size();i+=4){unsigned bits;memcpy(&bits,output.data()+i,4);printf("0x%08x,",bits);}printf("};\n");return true;
}
int main(){JxlMemoryManager memory;if(!jxl::MemoryManagerInit(&memory,nullptr))return 1;printf("// Generated by tests/unit/float_extra_upsampling_oracle.cc.\n");for(unsigned id=0;id<18;++id)if(!Generate(&memory,id))return 2;}
