// Enable legal filters over lossless floating modular planes without prefiltering.
#include <cstdio>
#include <cstring>
#include <vector>
#include "jxl/cms.h"
#include "jxl/decode.h"
#include "lib/jxl/enc_frame.h"
#include "lib/jxl/enc_fields.h"
#include "lib/jxl/memory_manager_internal.h"
static jxl::Status Generate(JxlMemoryManager* memory,unsigned id){
 const unsigned width=31,height=19;
 jxl::CodecMetadata metadata;JXL_RETURN_IF_ERROR(metadata.size.Set(width,height));metadata.m.SetFloat32Samples();metadata.m.xyb_encoded=false;metadata.m.color_encoding=jxl::ColorEncoding::SRGB();
 jxl::BitWriter writer(memory);JXL_RETURN_IF_ERROR(jxl::WriteCodestreamHeaders(&metadata,&writer,nullptr));writer.ZeroPadToByte();const size_t start=writer.BitsWritten()/8;
 jxl::CompressParams params;params.SetLossless();params.gaborish=jxl::Override::kOff;params.epf=0;params.patches=jxl::Override::kOff;params.speed_tier=jxl::SpeedTier::kThunder;JXL_RETURN_IF_ERROR(jxl::ParamsPostInit(&params));
 jxl::ImageBundle bundle(memory,&metadata.m);JXL_ASSIGN_OR_RETURN(jxl::Image3F image,jxl::Image3F::Create(memory,width,height));
 for(unsigned c=0;c<3;++c)for(unsigned y=0;y<height;++y)for(unsigned x=0;x<width;++x){
  float value=float(int((x*13+y*7+c*29)%300)-20)/255.f;
  unsigned bits;memcpy(&bits,&value,4);
  if(x==0&&y==0)bits=0x7f800000;
  if(x==5&&y==5)bits=0xff800000;
  if(x==width-2&&y==height-2)bits=0x7fc12345;
  if(x==15&&y==9)bits=0x80000000;
  memcpy(&image.PlaneRow(c,y)[x],&bits,4);
 }
 JXL_RETURN_IF_ERROR(bundle.SetFromImage(std::move(image),metadata.m.color_encoding));
 jxl::FrameInfo info;info.is_last=true;
 JXL_RETURN_IF_ERROR(jxl::EncodeFrame(memory,params,info,&metadata,bundle,*JxlGetDefaultCms(),nullptr,&writer,nullptr));writer.ZeroPadToByte();
 auto span=writer.GetSpan();jxl::BitReader reader(jxl::Bytes(span.data()+start,span.size()-start));jxl::FrameHeader header(&metadata);
 JXL_RETURN_IF_ERROR(jxl::ReadFrameHeader(&reader,&header));JXL_RETURN_IF_ERROR(reader.JumpToByteBoundary());const size_t payload=start+reader.TotalBitsConsumed()/8;JXL_RETURN_IF_ERROR(reader.Close());
 if(header.encoding!=jxl::FrameEncoding::kModular||header.loop_filter.gab||header.loop_filter.epf_iters)return false;
 header.loop_filter.gab=id>=4;header.loop_filter.epf_iters=id%4;
 jxl::BitWriter replacement(memory);JXL_RETURN_IF_ERROR(jxl::WriteFrameHeader(header,&replacement,nullptr));replacement.ZeroPadToByte();
 std::vector<unsigned char> bytes(span.begin(),span.begin()+start);auto changed=replacement.GetSpan();bytes.insert(bytes.end(),changed.begin(),changed.end());bytes.insert(bytes.end(),span.begin()+payload,span.end());
 jxl::BitReader check(jxl::Bytes(bytes.data()+start,bytes.size()-start));jxl::FrameHeader actual(&metadata);JXL_RETURN_IF_ERROR(jxl::ReadFrameHeader(&check,&actual));JXL_RETURN_IF_ERROR(check.Close());
 if(actual.loop_filter.gab!=(id>=4)||actual.loop_filter.epf_iters!=id%4||actual.encoding!=jxl::FrameEncoding::kModular)return false;
 auto* dec=JxlDecoderCreate(nullptr);JxlDecoderSubscribeEvents(dec,JXL_DEC_FULL_IMAGE);JxlDecoderSetInput(dec,bytes.data(),bytes.size());JxlDecoderCloseInput(dec);
 JxlPixelFormat format={3,JXL_TYPE_FLOAT,JXL_NATIVE_ENDIAN,0};std::vector<unsigned char> output(width*height*3*4);unsigned frames=0;
 for(;;){auto status=JxlDecoderProcessInput(dec);if(status==JXL_DEC_SUCCESS)break;if(status==JXL_DEC_NEED_IMAGE_OUT_BUFFER){if(JxlDecoderSetImageOutBuffer(dec,&format,output.data(),output.size())!=JXL_DEC_SUCCESS)return false;}else if(status==JXL_DEC_FULL_IMAGE)++frames;else{fprintf(stderr,"float filter id=%u status=%d\n",id,status);return false;}}
 JxlDecoderDestroy(dec);if(frames!=1)return false;
 printf("pub const bytes_%u=[_]u8{",id);for(auto b:bytes)printf("%u,",b);printf("};\npub const float_%u=[_]u32{",id);
 for(size_t i=0;i<output.size();i+=4){unsigned bits;memcpy(&bits,output.data()+i,4);printf("0x%08x,",bits);}printf("};\n");return true;
}
int main(){JxlMemoryManager memory;if(!jxl::MemoryManagerInit(&memory,nullptr))return 1;printf("// Generated by tests/unit/float_filter_oracle.cc.\n");for(unsigned id=0;id<8;++id)if(!Generate(&memory,id))return 2;}
