// Non-finite and signed-zero samples through upstream's public encoder/decoder.
#include <cstdio>
#include <cstring>
#include <vector>
#include "jxl/encode.h"
#include "jxl/decode.h"
#include "jxl/color_encoding.h"
int main(){
 printf("// Generated by tests/unit/float_special_oracle.cc.\n");
 const unsigned bits[]={16,24,32,11},exps[]={5,7,8,4};
 for(unsigned id=0;id<4;++id){
  JxlBasicInfo info;JxlEncoderInitBasicInfo(&info);info.xsize=8;info.ysize=1;info.bits_per_sample=bits[id];info.exponent_bits_per_sample=exps[id];info.uses_original_profile=JXL_TRUE;info.num_color_channels=3;info.num_extra_channels=1;info.alpha_bits=bits[id];info.alpha_exponent_bits=exps[id];
  auto* enc=JxlEncoderCreate(nullptr);if(JxlEncoderSetBasicInfo(enc,&info)!=JXL_ENC_SUCCESS)return 1;JxlColorEncoding color;JxlColorEncodingSetToSRGB(&color,JXL_FALSE);if(JxlEncoderSetColorEncoding(enc,&color)!=JXL_ENC_SUCCESS)return 2;
  auto* settings=JxlEncoderFrameSettingsCreate(enc,nullptr);if(JxlEncoderSetFrameLossless(settings,JXL_TRUE)!=JXL_ENC_SUCCESS||JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_MODULAR,1)!=JXL_ENC_SUCCESS)return 3;
  const unsigned words[]={0,0x80000000,0x7f800000,0xff800000,0x7fc00000,0xffc00000,0x3f800000,0xbf800000};float input[32];for(unsigned i=0;i<32;++i)memcpy(input+i,words+(i+i/4)%8,4);
  JxlPixelFormat format={4,JXL_TYPE_FLOAT,JXL_NATIVE_ENDIAN,0};if(JxlEncoderAddImageFrame(settings,&format,input,sizeof(input))!=JXL_ENC_SUCCESS)return 4;JxlEncoderCloseInput(enc);
  std::vector<unsigned char> bytes(1<<20);auto* next=bytes.data();size_t avail=bytes.size();if(JxlEncoderProcessOutput(enc,&next,&avail)!=JXL_ENC_SUCCESS)return 5;bytes.resize(bytes.size()-avail);JxlEncoderDestroy(enc);
  printf("pub const bytes_%u=[_]u8{",id);for(auto b:bytes)printf("%u,",b);printf("};\n");
  for(unsigned kind=0;kind<3;++kind){
   auto* dec=JxlDecoderCreate(nullptr);JxlDecoderSubscribeEvents(dec,JXL_DEC_BASIC_INFO|JXL_DEC_FULL_IMAGE);JxlDecoderSetInput(dec,bytes.data(),bytes.size());JxlDecoderCloseInput(dec);format.data_type=kind==2?JXL_TYPE_FLOAT16:kind?JXL_TYPE_FLOAT:JXL_TYPE_UINT8;std::vector<unsigned char> output(32*(kind==2?2:kind?4:1));unsigned frames=0;
   for(;;){auto status=JxlDecoderProcessInput(dec);if(status==JXL_DEC_SUCCESS)break;if(status==JXL_DEC_NEED_IMAGE_OUT_BUFFER){if(JxlDecoderSetImageOutBuffer(dec,&format,output.data(),output.size())!=JXL_DEC_SUCCESS)return 6;}else if(status==JXL_DEC_FULL_IMAGE)++frames;else if(status==JXL_DEC_BASIC_INFO){JxlBasicInfo actual;if(JxlDecoderGetBasicInfo(dec,&actual)!=JXL_DEC_SUCCESS||actual.bits_per_sample!=info.bits_per_sample||actual.exponent_bits_per_sample!=info.exponent_bits_per_sample||actual.alpha_bits!=info.alpha_bits||actual.alpha_exponent_bits!=info.alpha_exponent_bits||!actual.uses_original_profile)return 9;}else return 7;}JxlDecoderDestroy(dec);if(frames!=1)return 8;
   printf("pub const %s_%u=[_]%s{",kind==2?"half_bits":kind?"float_bits":"pixels",id,kind==2?"u16":kind?"u32":"u8");if(kind==2){for(size_t i=0;i<output.size();i+=2){unsigned short word;memcpy(&word,output.data()+i,2);printf("0x%04x,",word);}}else if(kind){for(size_t i=0;i<output.size();i+=4){unsigned word;memcpy(&word,output.data()+i,4);printf("0x%08x,",word);}}else for(auto b:output)printf("%u,",b);printf("};\n");
  }
 }
}
