// Independent admission decisions for upstream's wide-gradient lookup path.
#include <cstdio>
#include <cstdint>
#include "lib/jxl/modular/encoding/encoding.h"
int main(){
 puts("// Generated by tests/unit/gradient_lookup_oracle.cc.\npub const cases=[_][8]i64{");
 const int limits[]={INT32_MIN,-8194,-8193,-8192,-1,0,8190,8191,8192,INT32_MAX};
 for(int a:limits)for(int b:limits)for(unsigned variant=0;variant<6;++variant){
  const int p0=variant==1?10:9,p1=variant==2?8:9,offset=variant==3?1:0,multiplier=variant==4?2:1;
  const auto predictor=variant==5?jxl::Predictor::Zero:jxl::Predictor::Gradient;
  jxl::Tree tree={jxl::PropertyDecisionNode::Split(p0,a,1,2),jxl::PropertyDecisionNode::Split(p1,b,3,4),jxl::PropertyDecisionNode::Leaf(predictor,offset,multiplier),jxl::PropertyDecisionNode::Leaf(predictor,offset,multiplier),jxl::PropertyDecisionNode::Leaf(predictor,offset,multiplier)};
  std::array<jxl::pixel_type,2> statics={{1,0}};size_t count;bool wp,wp_only,gradient;
  auto flat=jxl::FilterTree(tree,statics,&count,&wp,&wp_only,&gradient);
  auto lut=jxl::make_unique<jxl::TreeLut<uint16_t,false,false>>();
  bool accepted=gradient&&jxl::TreeToLookupTable(flat,*lut);
  printf(".{%d,%d,%d,%d,%u,%d,%d,%d},\n",p0,a,p1,b,unsigned(predictor),offset,multiplier,accepted);
 }
 puts("};");
}
