#include <cstdio>
#include <cstring>
#include <vector>
#include "jxl/decode.h"
int main(int argc,char**argv){
 if(argc!=2)return 1;FILE* file=fopen(argv[1],"rb");if(!file)return 2;fseek(file,0,SEEK_END);long size=ftell(file);rewind(file);std::vector<unsigned char> bytes(size);if(fread(bytes.data(),1,bytes.size(),file)!=bytes.size())return 3;fclose(file);
 printf("// Generated by tests/unit/gray_profile_oracle.cc from grayscale.jxl.\n");
 for(unsigned kind=0;kind<3;++kind){
  auto* dec=JxlDecoderCreate(nullptr);JxlDecoderSubscribeEvents(dec,JXL_DEC_BASIC_INFO|JXL_DEC_COLOR_ENCODING|JXL_DEC_FULL_IMAGE);JxlDecoderSetInput(dec,bytes.data(),bytes.size());JxlDecoderCloseInput(dec);
  JxlPixelFormat format={kind==2?3u:1u,kind==1?JXL_TYPE_FLOAT:JXL_TYPE_UINT8,JXL_NATIVE_ENDIAN,0};std::vector<unsigned char> output;unsigned frames=0;
  for(;;){auto status=JxlDecoderProcessInput(dec);if(status==JXL_DEC_SUCCESS)break;
   if(status==JXL_DEC_BASIC_INFO){JxlBasicInfo info;if(JxlDecoderGetBasicInfo(dec,&info)!=JXL_DEC_SUCCESS||info.xsize!=200||info.ysize!=200||info.num_color_channels!=1||info.uses_original_profile)return 4;}
   else if(status==JXL_DEC_COLOR_ENCODING){
    for(unsigned target=0;target<2;++target){auto t=target?JXL_COLOR_PROFILE_TARGET_DATA:JXL_COLOR_PROFILE_TARGET_ORIGINAL;JxlColorEncoding color;auto s=JxlDecoderGetColorAsEncodedProfile(dec,t,&color);
     if(kind==0){fprintf(stderr,"target=%u status=%d space=%d tf=%d\n",target,s,s==JXL_DEC_SUCCESS?color.color_space:-1,s==JXL_DEC_SUCCESS?color.transfer_function:-1);
      size_t n;if(JxlDecoderGetICCProfileSize(dec,t,&n)!=JXL_DEC_SUCCESS)return 5;std::vector<unsigned char>icc(n);if(JxlDecoderGetColorAsICCProfile(dec,t,icc.data(),n)!=JXL_DEC_SUCCESS)return 6;
      printf("pub const %s_icc=[_]u8{",target?"data":"original");for(auto b:icc)printf("%u,",b);printf("};\n");
     }
    }
   }else if(status==JXL_DEC_NEED_IMAGE_OUT_BUFFER){size_t n;if(JxlDecoderImageOutBufferSize(dec,&format,&n)!=JXL_DEC_SUCCESS)return 7;output.resize(n);if(JxlDecoderSetImageOutBuffer(dec,&format,output.data(),n)!=JXL_DEC_SUCCESS)return 8;}
   else if(status==JXL_DEC_FULL_IMAGE)++frames;else return 9;
  }JxlDecoderDestroy(dec);if(frames!=1)return 10;
  printf("pub const pixels_%u=[_]%s{",kind,kind==1?"u32":"u8");if(kind==1){for(size_t i=0;i<output.size();i+=4){unsigned word;memcpy(&word,output.data()+i,4);printf("0x%08x,",word);}}else for(auto b:output)printf("%u,",b);printf("};\n");
 }
}
