// Independent long-prefix lookup tables from libjxl.
#include <cstdio>
#include <vector>
#include "lib/jxl/huffman_table.h"
#include "lib/jxl/dec_huffman.h"
#include "lib/jxl/base/span.h"
static void Mix(uint64_t& hash,uint32_t value){hash^=value;hash*=1099511628211ULL;}
int main(){
 printf("// Generated by tests/unit/huffman_secondary_oracle.cc using libjxl.\n");
 for(unsigned id=0;id<9;++id){
  std::vector<uint8_t> lengths;
  if(id<7){unsigned depth=9+id;for(unsigned n=1;n<depth;++n)lengths.push_back(n);lengths.push_back(depth);lengths.push_back(depth);}
  else lengths.assign(1u<<(id+2),id+2);
  uint16_t counts[16]={};for(auto length:lengths)++counts[length];
  jxl::HuffmanDecodingData code;code.table_.resize(65536);
  auto size=jxl::BuildHuffmanTable(code.table_.data(),8,lengths.data(),lengths.size(),counts);if(!size)return 1;
  uint64_t table_hash=14695981039346656037ULL,decode_hash=table_hash;
  for(unsigned i=0;i<size;++i){Mix(table_hash,code.table_[i].bits);Mix(table_hash,code.table_[i].value);}
  for(unsigned lookahead=0;lookahead<32768;++lookahead){unsigned char bytes[8]={static_cast<unsigned char>(lookahead),static_cast<unsigned char>(lookahead>>8)};jxl::BitReader bits(jxl::Bytes(bytes,8));auto symbol=code.ReadSymbol(&bits);Mix(decode_hash,symbol);Mix(decode_hash,bits.TotalBitsConsumed());if(!bits.Close())return 2;}
  printf("pub const lengths_%u=[_]u8{",id);for(auto n:lengths)printf("%u,",n);printf("};\npub const size_%u:usize=%u;\npub const table_hash_%u:u64=%llu;\npub const decode_hash_%u:u64=%llu;\n",id,size,id,(unsigned long long)table_hash,id,(unsigned long long)decode_hash);
 }
}
