// Reference samples from retained upstream block transforms, using scalar code.
#include <algorithm>
#include <cstdint>
#include <cstdio>
#include <vector>
#include "lib/jxl/ac_strategy.h"
#include "lib/jxl/dec_transforms-inl.h"

size_t Position(size_t i, size_t width, size_t height) {
	if (width * height == 64) return i;
	if (i < 4) return (i / 2) * (height - 1) * width + (i % 2) * (width - 1);
	return (i * 4051 + 17) % (width * height);
}

int main() {
	printf("// Generated by tests/unit/inverse_transform_oracle.cc. Samples scaled by 2^20.\n");
	printf("pub const samples = [27][64]i32{\n");
	for (uint32_t raw = 0; raw < 27; ++raw) {
		const auto strategy = jxl::AcStrategy::FromRawStrategy(raw);
		const size_t width = strategy.covered_blocks_x() * 8;
		const size_t height = strategy.covered_blocks_y() * 8;
		const size_t size = width * height;
		std::vector<float> coefficients(size), pixels(size), scratch(5 * size + 128);
		for (size_t i = 0; i < size; ++i) coefficients[i] = (static_cast<int>(i % 23) - 11) / 1024.0f;
		jxl::HWY_NAMESPACE::TransformToPixels(static_cast<jxl::AcStrategyType>(raw), coefficients.data(),
			pixels.data(), width, scratch.data());
		printf("\t.{");
		for (size_t i = 0; i < 64; ++i) {
			const size_t position = Position(i, width, height);
			printf("%d,", static_cast<int>(pixels[position] * (1 << 20)));
		}
		printf("},\n");
	}
	printf("};\npub const positions = [27][64]u32{\n");
	for (uint32_t raw = 0; raw < 27; ++raw) {
		const auto strategy = jxl::AcStrategy::FromRawStrategy(raw);
		const size_t width = strategy.covered_blocks_x() * 8;
		const size_t height = strategy.covered_blocks_y() * 8;
		printf("\t.{");
		for (size_t i = 0; i < 64; ++i)
			printf("%zu,", Position(i, width, height));
		printf("},\n");
	}
	printf("};\n");
	printf("pub const low_frequency = [27][]const i32{\n");
	for (uint32_t raw = 0; raw < 27; ++raw) {
		const auto strategy = jxl::AcStrategy::FromRawStrategy(raw);
		const size_t width = strategy.covered_blocks_x();
		const size_t height = strategy.covered_blocks_y();
		const size_t stride = width + 3;
		std::vector<float> dc(stride * height), coeff(64 * width * height), scratch(5 * width * height + 128);
		for (size_t y = 0; y < height; ++y)
			for (size_t x = 0; x < width; ++x)
				dc[y * stride + x] = (static_cast<int>((x * 3 + y * 7) % 19) - 9) / 128.0f;
		jxl::HWY_NAMESPACE::LowestFrequenciesFromDC(static_cast<jxl::AcStrategyType>(raw),
			dc.data(), stride, coeff.data(), scratch.data());
		printf("\t&.{");
		for (size_t y = 0; y < std::min(width, height); ++y)
			for (size_t x = 0; x < std::max(width, height); ++x)
				printf("%d,", static_cast<int>(coeff[y * 8 * std::max(width, height) + x] * (1 << 24)));
		printf("},\n");
	}
	printf("};\n");
}
