#include "jxl/encode.h"
#include "lib/jxl/jpeg/enc_jpeg_data.h"
#include "lib/jxl/memory_manager_internal.h"
#include <cstdio>
#include <vector>
jxl::Status Parse(JxlMemoryManager *memory, jxl::Bytes input,
				  std::unique_ptr<jxl::jpeg::JPEGData> *jpeg) {
	JXL_ASSIGN_OR_RETURN(*jpeg, jxl::jpeg::ParseJPG(memory, input));
	return true;
}
int main(int argc, char **argv) {
	JxlMemoryManager memory;
	if (!jxl::MemoryManagerInit(&memory, nullptr))
		return 1;
	printf("// Generated by tests/unit/jpeg_coefficients_oracle.cc.\n");
	for (int id = 0; id < argc - 1; ++id) {
		auto *file = fopen(argv[id + 1], "rb");
		if (!file)
			return 2;
		std::vector<uint8_t> input;
		uint8_t chunk[4096];
		size_t n;
		while ((n = fread(chunk, 1, sizeof(chunk), file)))
			input.insert(input.end(), chunk, chunk + n);
		bool failed = ferror(file);
		fclose(file);
		if (failed)
			return 3;
		std::unique_ptr<jxl::jpeg::JPEGData> jpeg;
		if (!Parse(&memory, jxl::Bytes(input), &jpeg))
			return 4;
		auto *encoder = JxlEncoderCreate(nullptr);
		if (!encoder)
			return 5;
		if (JxlEncoderStoreJPEGMetadata(encoder, JXL_TRUE) != JXL_ENC_SUCCESS)
			return 6;
		auto *settings = JxlEncoderFrameSettingsCreate(encoder, nullptr);
		if (JxlEncoderAddJPEGFrame(settings, input.data(), input.size()) !=
			JXL_ENC_SUCCESS)
			return 7;
		JxlEncoderCloseInput(encoder);
		std::vector<uint8_t> encoded;
		for (;;) {
			uint8_t *out = chunk;
			size_t available = sizeof(chunk);
			auto status = JxlEncoderProcessOutput(encoder, &out, &available);
			encoded.insert(encoded.end(), chunk, out);
			if (status == JXL_ENC_SUCCESS)
				break;
			if (status != JXL_ENC_NEED_MORE_OUTPUT)
				return 8;
		}
		JxlEncoderDestroy(encoder);
		printf("pub const bytes_%d=[_]u8{", id);
		for (auto b : encoded)
			printf("%u,", b);
		printf("};\n");
		printf("pub const jpeg_%d=[_]u8{", id);
		for (auto b : input)
			printf("%u,", b);
		printf("};\n");
		printf("pub const dimensions_%d=[_]usize{%u,%u};\n", id, jpeg->width,
			   jpeg->height);
		printf("pub const components_%d=[_][5]u32{", id);
		for (auto &c : jpeg->components)
			printf(".{%u,%u,%u,%u,%u},", c.id, c.h_samp_factor, c.v_samp_factor,
				   c.width_in_blocks, c.height_in_blocks);
		printf("};\n");
		for (size_t c = 0; c < jpeg->components.size(); ++c) {
			printf("pub const coeffs_%d_%zu=[_]i16{", id, c);
			for (auto v : jpeg->components[c].coeffs)
				printf("%d,", v);
			printf("};\n");
		}
		printf("pub const quant_%d=[_][64]i32{", id);
		for (auto &q : jpeg->quant) {
			printf(".{");
			for (auto v : q.values)
				printf("%d,", v);
			printf("},");
		}
		printf("};\n");
	}
}
