#include "jxl/encode.h"
#include "lib/jxl/jpeg/dec_jpeg_data_writer.h"
#include "lib/jxl/jpeg/enc_jpeg_data.h"
#include "lib/jxl/memory_manager_internal.h"
#include <algorithm>
#include <cstdio>
#include <cstring>
#include <vector>
jxl::Status Parse(JxlMemoryManager *memory, jxl::Bytes input,
				  std::unique_ptr<jxl::jpeg::JPEGData> *jpeg) {
	JXL_ASSIGN_OR_RETURN(*jpeg, jxl::jpeg::ParseJPG(memory, input));
	return true;
}
int main(int argc, char **argv) {
	JxlMemoryManager memory;
	if (!jxl::MemoryManagerInit(&memory, nullptr))
		return 1;
	printf("// Generated by tests/unit/jpeg_writer_oracle.cc.\n");
	const bool details = argc == 3 && std::strcmp(argv[2], "--details") == 0;
	const bool metadata = argc == 3 && std::strcmp(argv[2], "--metadata") == 0;
	const bool eob = argc == 3 && std::strcmp(argv[2], "--eob") == 0;
	const bool synthetic =
		eob || metadata || details ||
		(argc == 3 && std::strcmp(argv[2], "--synthetic") == 0);
	for (int id = 0; id < (eob		   ? 2
						   : metadata  ? 1
						   : details   ? 16
						   : synthetic ? 80
									   : argc - 1);
		 ++id) {
		auto *file = fopen(argv[synthetic ? 1 : id + 1], "rb");
		if (!file)
			return 2;
		std::vector<uint8_t> input;
		uint8_t chunk[4096];
		size_t n;
		while ((n = fread(chunk, 1, sizeof(chunk), file)))
			input.insert(input.end(), chunk, chunk + n);
		bool failed = ferror(file);
		fclose(file);
		if (failed)
			return 3;
		std::unique_ptr<jxl::jpeg::JPEGData> jpeg;
		if (!Parse(&memory, jxl::Bytes(input), &jpeg))
			return 4;
		if (synthetic) {
			const bool gray = eob || id >= 72, rgb = id >= 64 && !gray;
			unsigned hs[3] = {1, 1, 1}, vs[3] = {1, 1, 1}, max_h = 1, max_v = 1;
			for (unsigned c = 0; c < 3; ++c) {
				unsigned mode = !eob && id < 64 ? (id >> (2 * c)) & 3 : 0;
				hs[c] = (mode == 1 || mode == 2) ? 2 : 1;
				vs[c] = (mode == 2 || mode == 3) ? 2 : 1;
				max_h = std::max(max_h, hs[c]);
				max_v = std::max(max_v, vs[c]);
			}
			jpeg->width = eob ? 2048 : 17 + (id % 2) * 16;
			jpeg->height = eob ? 1025 : 9 + (id % 3) * 8;
			jpeg->components.resize(gray ? 1 : 3);
			jpeg->scan_info[0].num_components = gray ? 1 : 3;
			jpeg->restart_interval = !eob && id % 2 ? 3 : 0;
			if (gray)
				jpeg->quant[1].values = jpeg->quant[0].values;
			if (id & 8) {
				for (auto &marker : jpeg->marker_order)
					if (marker == 0xc0)
						marker = 0xc1;
				for (size_t q = 0; q < jpeg->quant.size(); ++q) {
					auto &table = jpeg->quant[q];
					table.precision = 1;
					for (size_t i = 0; i < 64; ++i)
						table.values[i] =
							i == 0	 ? q + 1
							: i == 1 ? 65535
									 : 256 + (i * 977 + q * 17) % 65280;
				}
				if (gray)
					jpeg->quant[1].values = jpeg->quant[0].values;
			}
			if (rgb) {
				jpeg->app_data.clear();
				jpeg->app_marker_type.clear();
				jpeg->marker_order.erase(
					std::remove_if(
						jpeg->marker_order.begin(), jpeg->marker_order.end(),
						[](uint8_t marker) { return (marker & 0xf0) == 0xe0; }),
					jpeg->marker_order.end());
			}
			for (size_t c = 0; c < jpeg->components.size(); ++c) {
				auto &component = jpeg->components[c];
				component.id = rgb ? "RGB"[c] : c + 1;
				component.h_samp_factor = hs[c];
				component.v_samp_factor = vs[c];
				component.width_in_blocks =
					((jpeg->width + 8 * max_h - 1) / (8 * max_h)) *
					component.h_samp_factor;
				component.height_in_blocks =
					((jpeg->height + 8 * max_v - 1) / (8 * max_v)) *
					component.v_samp_factor;
				component.coeffs.resize(component.width_in_blocks *
										component.height_in_blocks * 64);
				for (size_t i = 0; i < component.coeffs.size(); ++i)
					component.coeffs[i] =
						eob ? (id == 1 && i % 64 == 1 ? 2 : 0)
						: (i % 64 == 0)
							? int((i / 64 * 11 + c * 23) % 181) - 90
							: (i % 7 == 0 ? int((i * 13 + c * 7) % 11) - 5 : 0);
			}
			// Construct independently encoded progressive scans, including
			// DC/AC refinement and separate spectral bands. Full alphabets
			// permit EOB runs.
			jpeg->huffman_code.clear();
			for (unsigned ac = 0; ac != 2; ++ac) {
				jxl::jpeg::JPEGHuffmanCode table{};
				table.slot_id = ac ? 16 : 0;
				table.is_last = true;
				if (ac) {
					table.counts[8] = 128;
					table.counts[9] = 129;
				} else
					table.counts[4] = 13;
				for (unsigned v = 0; v < (ac ? 257u : 13u); ++v)
					table.values[v] = (v == (ac ? 256u : 12u)) ? 256 : v;
				jpeg->huffman_code.push_back(table);
			}
			jpeg->marker_order.erase(std::remove_if(jpeg->marker_order.begin(),
													jpeg->marker_order.end(),
													[](uint8_t marker) {
														return marker == 0xc4 ||
															   marker == 0xda ||
															   marker == 0xd9;
													}),
									 jpeg->marker_order.end());
			for (auto &marker : jpeg->marker_order)
				if (marker == 0xc0 || marker == 0xc1)
					marker = 0xc2;
			jpeg->marker_order.push_back(0xc4);
			jpeg->marker_order.push_back(0xc4);
			jpeg->scan_info.clear();
			const unsigned initial = 1 + (id % 2);
			if (details)
				for (auto &component : jpeg->components)
					for (size_t block = 0; block < component.coeffs.size();
						 block += 64)
						for (size_t k = 48; k < 64; ++k)
							component.coeffs[block +
											 jxl::jpeg::kJPEGNaturalOrder[k]] =
								0;
			for (int bit = initial; bit >= 0; --bit) {
				const unsigned ah = bit == int(initial) ? 0 : bit + 1;
				jxl::jpeg::JPEGScanInfo dc{};
				dc.num_components = jpeg->components.size();
				dc.Ss = dc.Se = 0;
				dc.Ah = ah;
				dc.Al = bit;
				for (unsigned c = 0; c < dc.num_components; ++c)
					dc.components[c] = {c, 0, 0};
				jpeg->scan_info.push_back(dc);
				jpeg->marker_order.push_back(0xda);
				for (unsigned c = 0; c < jpeg->components.size(); ++c)
					for (unsigned band = 0; band != 2; ++band) {
						jxl::jpeg::JPEGScanInfo ac{};
						ac.num_components = 1;
						ac.components[0] = {c, 0, 0};
						ac.Ss = band ? 9 : 1;
						ac.Se = band ? 63 : 8;
						ac.Ah = ah;
						ac.Al = bit;
						if (details)
							ac.reset_points = {2, 4};
						if (details && ah == 0 && band == 1)
							ac.extra_zero_runs = {{0, 1}};
						jpeg->scan_info.push_back(ac);
						jpeg->marker_order.push_back(0xda);
					}
			}
			jpeg->marker_order.push_back(0xd9);
			if (metadata) {
				bool split = false;
				for (size_t a = 0; a < jpeg->app_data.size(); ++a) {
					const auto original = jpeg->app_data[a];
					if (original.size() < 19 ||
						std::memcmp(original.data() + 3, "ICC_PROFILE", 12) !=
							0)
						continue;
					const size_t middle = 17 + (original.size() - 17) / 2;
					std::vector<uint8_t> first(original.begin(),
											   original.begin() + middle),
						second(original.begin(), original.begin() + 17);
					second.insert(second.end(), original.begin() + middle,
								  original.end());
					first[1] = (first.size() - 1) >> 8;
					first[2] = (first.size() - 1) & 255;
					first[15] = 1;
					first[16] = 2;
					second[1] = (second.size() - 1) >> 8;
					second[2] = (second.size() - 1) & 255;
					second[15] = 2;
					second[16] = 2;
					jpeg->app_data[a] = first;
					jpeg->app_data.insert(jpeg->app_data.begin() + a + 1,
										  second);
					size_t app_index = 0;
					for (auto it = jpeg->marker_order.begin();
						 it != jpeg->marker_order.end(); ++it)
						if ((*it & 0xf0) == 0xe0) {
							if (app_index++ == a) {
								jpeg->marker_order.insert(it + 1, 0xe2);
								break;
							}
						}
					split = true;
					break;
				}
				if (!split)
					return 15;
			}
			input.clear();
			if (!jxl::jpeg::WriteJpeg(
					*jpeg, [&](const uint8_t *bytes, size_t count) {
						input.insert(input.end(), bytes, bytes + count);
						return count;
					}))
				return 9;
			if (!Parse(&memory, jxl::Bytes(input), &jpeg))
				return 10;
			if (details) {
				jpeg->has_zero_padding_bit = !jpeg->padding_bits.empty();
				for (size_t bit = 0; bit < jpeg->padding_bits.size(); ++bit)
					jpeg->padding_bits[bit] = (bit + id) & 1;
				jpeg->com_data.push_back({0xfe, 0, 7, 'a', 0, 255, 'b', 0});
				jpeg->marker_order.insert(jpeg->marker_order.begin(), 0xfe);
				jpeg->marker_order.insert(jpeg->marker_order.end() - 1, 0xff);
				jpeg->inter_marker_data.push_back({0, 17, 0, 33});
				jpeg->tail_data = {0, 255, 0, 77};
				input.clear();
				if (!jxl::jpeg::WriteJpeg(
						*jpeg, [&](const uint8_t *bytes, size_t count) {
							input.insert(input.end(), bytes, bytes + count);
							return count;
						}))
					return 13;
				if (!Parse(&memory, jxl::Bytes(input), &jpeg))
					return 14;
			}
		}
		auto *encoder = JxlEncoderCreate(nullptr);
		if (!encoder)
			return 5;
		if (JxlEncoderStoreJPEGMetadata(encoder, JXL_TRUE) != JXL_ENC_SUCCESS)
			return 6;
		auto *settings = JxlEncoderFrameSettingsCreate(encoder, nullptr);
		if (synthetic) {
			if (JxlEncoderFrameSettingsSetOption(
					settings, JXL_ENC_FRAME_SETTING_JPEG_RECON_CFL, id % 2) !=
				JXL_ENC_SUCCESS)
				return 11;
			if (JxlEncoderFrameSettingsSetOption(
					settings, JXL_ENC_FRAME_SETTING_PROGRESSIVE_AC,
					(id & 4) ? 1 : 0) != JXL_ENC_SUCCESS)
				return 12;
		}
		if (JxlEncoderAddJPEGFrame(settings, input.data(), input.size()) !=
			JXL_ENC_SUCCESS)
			return 7;
		JxlEncoderCloseInput(encoder);
		std::vector<uint8_t> encoded;
		for (;;) {
			uint8_t *out = chunk;
			size_t available = sizeof(chunk);
			auto status = JxlEncoderProcessOutput(encoder, &out, &available);
			encoded.insert(encoded.end(), chunk, out);
			if (status == JXL_ENC_SUCCESS)
				break;
			if (status != JXL_ENC_NEED_MORE_OUTPUT)
				return 8;
		}
		JxlEncoderDestroy(encoder);
		printf("pub const bytes_%d=[_]u8{", id);
		for (auto b : encoded)
			printf("%u,", b);
		printf("};\n");
		printf("pub const jpeg_%d=[_]u8{", id);
		for (auto b : input)
			printf("%u,", b);
		printf("};\n");
		printf("pub const dimensions_%d=[_]usize{%u,%u};\n", id, jpeg->width,
			   jpeg->height);
		printf("pub const components_%d=[_][5]u32{", id);
		for (auto &c : jpeg->components)
			printf(".{%u,%u,%u,%u,%u},", c.id, c.h_samp_factor, c.v_samp_factor,
				   c.width_in_blocks, c.height_in_blocks);
		printf("};\n");
		for (size_t c = 0; !eob && c < jpeg->components.size(); ++c) {
			printf("pub const coeffs_%d_%zu=[_]i16{", id, c);
			for (auto v : jpeg->components[c].coeffs)
				printf("%d,", v);
			printf("};\n");
		}
		printf("pub const quant_%d=[_][64]i32{", id);
		for (auto &q : jpeg->quant) {
			printf(".{");
			for (auto v : q.values)
				printf("%d,", v);
			printf("},");
		}
		printf("};\n");
	}
}
