#include "lib/jxl/jpeg/dec_jpeg_data.h"
#include "lib/jxl/jpeg/enc_jpeg_data.h"
#include "lib/jxl/memory_manager_internal.h"
#include <cstdio>
#include <vector>
jxl::Status Parse(JxlMemoryManager *memory, jxl::Bytes input,
				  std::unique_ptr<jxl::jpeg::JPEGData> *jpeg) {
	JXL_ASSIGN_OR_RETURN(*jpeg, jxl::jpeg::ParseJPG(memory, input));
	return true;
}
int main(int argc, char **argv) {
	JxlMemoryManager memory;
	if (!jxl::MemoryManagerInit(&memory, nullptr))
		return 1;
	printf("// Generated by tests/unit/jpeg_reconstruction_oracle.cc.\n");
	for (int id = 0; id < argc - 1; ++id) {
		auto *file = fopen(argv[id + 1], "rb");
		if (!file)
			return 2;
		std::vector<uint8_t> input;
		uint8_t chunk[4096];
		size_t n;
		while ((n = fread(chunk, 1, sizeof(chunk), file)))
			input.insert(input.end(), chunk, chunk + n);
		bool failed = ferror(file);
		fclose(file);
		if (failed)
			return 3;
		std::unique_ptr<jxl::jpeg::JPEGData> jpeg;
		if (!Parse(&memory, jxl::Bytes(input), &jpeg))
			return 4;
		// Exercise reconstruction metadata independently of the image
		// coefficients.
		if (id >= 3) {
			jpeg->tail_data = {0, 255, 65, 66, 0};
			jpeg->marker_order.insert(jpeg->marker_order.end() - 1, 0xff);
			jpeg->inter_marker_data.push_back({255, 0, 17, 0, 255});
			jpeg->has_zero_padding_bit = true;
			jpeg->padding_bits = {1, 0, 1, 0, 0, 1, 1};
			jpeg->scan_info[0].reset_points = {0, 8, 64, 1024};
			jpeg->scan_info[0].extra_zero_runs = {{0, 1}, {63, 2}, {200, 3}};
			for (size_t c = 0; c < jpeg->components.size(); ++c)
				jpeg->components[c].id = id == 3 ? "RGB"[c] : 17 + c * 11;
			for (unsigned i = 0; i < 2; ++i) {
				std::vector<uint8_t> app = {
					0xe2, 0,   18,	'I', 'C', 'C', '_', 'P',
					'R',  'O', 'F', 'I', 'L', 'E', 0,	uint8_t(i + 1),
					2,	  65,  66};
				jpeg->app_data.push_back(app);
				auto pos = jpeg->marker_order.begin();
				while (pos != jpeg->marker_order.end() && (*pos & 0xf0) == 0xe0)
					++pos;
				jpeg->marker_order.insert(pos, 0xe2);
			}
			if (id == 4) {
				jpeg->quant[0].precision = 1;
				jxl::jpeg::JPEGHuffmanCode empty{};
				empty.is_last = true;
				jpeg->huffman_code.insert(jpeg->huffman_code.begin(), empty);
				jpeg->marker_order.insert(jpeg->marker_order.begin(), 0xc4);
			}
			if (id == 5) {
				jpeg->components.resize(1);
				jpeg->components[0].id = 1;
				jpeg->components[0].quant_idx = 0;
				jpeg->quant.resize(1);
				jpeg->scan_info[0].num_components = 1;
				jpeg->scan_info[0].components[0].comp_idx = 0;
				jpeg->padding_bits.clear();
			}
		}
		std::vector<uint8_t> encoded;
		jxl::CompressParams params;
		if (!jxl::jpeg::EncodeJPEGData(&memory, *jpeg, &encoded, params))
			return 5;
		jxl::jpeg::JPEGData decoded;
		if (!jxl::jpeg::DecodeJPEGData(jxl::Bytes(encoded), &decoded))
			return 6;
		printf("pub const bytes_%d=[_]u8{", id);
		for (auto b : encoded)
			printf("%u,", b);
		printf("};\n");
		printf("pub const mutation_accept_%d=[_]bool{", id);
		for (size_t bit = 0; bit < encoded.size() * 8; ++bit) {
			encoded[bit / 8] ^= 1u << (bit % 8);
			jxl::jpeg::JPEGData mutated;
			printf("%s,",
				   jxl::jpeg::DecodeJPEGData(jxl::Bytes(encoded), &mutated)
					   ? "true"
					   : "false");
			encoded[bit / 8] ^= 1u << (bit % 8);
		}
		printf("};\n");
		printf("pub const truncation_accept_%d=[_]bool{", id);
		for (size_t size = 0; size < encoded.size(); ++size) {
			jxl::jpeg::JPEGData truncated;
			printf("%s,", jxl::jpeg::DecodeJPEGData(
							  jxl::Bytes(encoded.data(), size), &truncated)
							  ? "true"
							  : "false");
		}
		printf("};\n");
		printf("pub const markers_%d=[_]u8{", id);
		for (auto b : decoded.marker_order)
			printf("%u,", b);
		printf("};\n");
		printf("pub const components_%d=[_][2]u32{", id);
		for (auto &c : decoded.components)
			printf(".{%u,%u},", c.id, c.quant_idx);
		printf("};\n");
		printf("pub const quant_%d=[_][3]u32{", id);
		for (auto &q : decoded.quant)
			printf(".{%u,%u,%u},", q.precision, q.index, unsigned(q.is_last));
		printf("};\n");
		printf("pub const app_info_%d=[_][2]u32{", id);
		for (size_t i = 0; i < decoded.app_data.size(); ++i)
			printf(".{%u,%u},", unsigned(decoded.app_marker_type[i]),
				   unsigned(decoded.app_data[i].size()));
		printf("};\n");
		printf("pub const huff_info_%d=[_][2]u32{", id);
		for (auto &h : decoded.huffman_code)
			printf(".{%u,%u},", unsigned(h.slot_id), unsigned(h.is_last));
		printf("};\n");
		printf("pub const huff_counts_%d=[_][17]u32{", id);
		for (auto &h : decoded.huffman_code) {
			printf(".{");
			for (auto c : h.counts)
				printf("%u,", c);
			printf("},");
		}
		printf("};\n");
		printf("pub const huff_values_%d=[_][257]u32{", id);
		for (auto &h : decoded.huffman_code) {
			printf(".{");
			for (auto c : h.values)
				printf("%u,", c);
			printf("},");
		}
		printf("};\n");
		printf("pub const scans_%d=[_][6]u32{", id);
		for (auto &s : decoded.scan_info)
			printf(".{%u,%u,%u,%u,%u,%u},", s.num_components, s.Ss, s.Se, s.Al,
				   s.Ah, s.last_needed_pass);
		printf("};\n");
		printf("pub const scan_components_%d=[_][3][3]u32{", id);
		for (auto &s : decoded.scan_info) {
			printf(".{");
			for (size_t i = 0; i < 3; ++i) {
				if (i < s.num_components) {
					auto &c = s.components[i];
					printf(".{%u,%u,%u},", c.comp_idx, c.ac_tbl_idx,
						   c.dc_tbl_idx);
				} else
					printf(".{0,0,0},");
			}
			printf("},");
		}
		printf("};\n");
		for (size_t i = 0; i < decoded.scan_info.size(); ++i) {
			auto &s = decoded.scan_info[i];
			printf("pub const reset_%d_%zu=[_]u32{", id, i);
			for (auto p : s.reset_points)
				printf("%u,", p);
			printf("};\n");
			printf("pub const zeros_%d_%zu=[_][2]u32{", id, i);
			for (auto p : s.extra_zero_runs)
				printf(".{%u,%u},", p.block_idx, p.num_extra_zero_runs);
			printf("};\n");
		}
		printf("pub const padding_%d=[_]u8{", id);
		for (auto b : decoded.padding_bits)
			printf("%u,", b);
		printf("};\n");
		printf("pub const has_zero_padding_%d=%s;\n", id,
			   decoded.has_zero_padding_bit ? "true" : "false");
		printf("pub const tail_%d=[_]u8{", id);
		for (auto b : decoded.tail_data)
			printf("%u,", b);
		printf("};\n");
		for (size_t i = 0; i < decoded.app_data.size(); ++i) {
			printf("pub const app_%d_%zu=[_]u8{", id, i);
			for (auto b : decoded.app_data[i])
				printf("%u,", b);
			printf("};\n");
		}
		for (size_t i = 0; i < decoded.com_data.size(); ++i) {
			printf("pub const comment_%d_%zu=[_]u8{", id, i);
			for (auto b : decoded.com_data[i])
				printf("%u,", b);
			printf("};\n");
		}
		for (size_t i = 0; i < decoded.inter_marker_data.size(); ++i) {
			printf("pub const inter_%d_%zu=[_]u8{", id, i);
			for (auto b : decoded.inter_marker_data[i])
				printf("%u,", b);
			printf("};\n");
		}
		printf("pub const "
			   "counts_%d=[_]usize{%zu,%zu,%zu,%zu,%zu,%zu,%zu,%u,%zu};\n",
			   id, decoded.components.size(), decoded.quant.size(),
			   decoded.huffman_code.size(), decoded.scan_info.size(),
			   decoded.app_data.size(), decoded.com_data.size(),
			   decoded.inter_marker_data.size(), decoded.restart_interval,
			   decoded.padding_bits.size());
	}
}
