// Quantization matrix samples from all large upstream VarDCT strategies.
#include <cmath>
#include <array>
#include <cstdio>
#include "lib/jxl/quant_weights.h"
#include "lib/jxl/dec_bit_reader.h"
#include "lib/jxl/memory_manager_internal.h"
int main(){
	JxlMemoryManager memory;if(!jxl::MemoryManagerInit(&memory,nullptr))return 1;
	jxl::DequantMatrices matrices;const std::array<uint8_t,1> data={1};jxl::BitReader reader(data);
	if(!matrices.Decode(&memory,&reader)||!reader.Close())return 2;
	if(!matrices.EnsureComputed(&memory,((1u<<27)-1)^((1u<<21)-1)))return 3;
	printf("// Generated by tests/unit/large_quant_oracle.cc. Samples scaled by 2^40.\npub const samples=[6][3][64]i64{\n");
	for(unsigned raw=21;raw<27;++raw){
		const auto strategy=jxl::AcStrategy::FromRawStrategy(raw);const size_t size=64*strategy.covered_blocks_x()*strategy.covered_blocks_y();
		printf(".{");for(size_t c=0;c<3;++c){const float* matrix=matrices.Matrix(static_cast<jxl::AcStrategyType>(raw),c);printf(".{");
			for(size_t i=0;i<64;++i){const size_t index=i==0?0:i==1?size-1:(i*4051+17)%size;printf("%lld,",std::llround(matrix[index]*(1ll<<40)));}printf("},");}
		printf("},\n");
	}
	printf("};\n");
}
