// Lossy fixtures and decoded RGB samples from the retained upstream public API.
#include <cstdio>
#include <vector>
#include "jxl/encode.h"
#include "jxl/decode.h"
#include "jxl/color_encoding.h"
int main() {
	printf("// Generated by tests/unit/modular_render_oracle.cc with upstream libjxl.\n");
	for (unsigned id=0;id<12;++id) {
		const unsigned width=19;
 const unsigned color_factors[12]={1,2,4,8,1,2,4,8,1,2,4,8};
 const unsigned extra_factors[12]={2,2,4,8,2,2,4,8,1,2,4,8};
		const unsigned height=13;
		std::vector<unsigned char> pixels(width*height*4);
		for(unsigned y=0;y<height;++y)for(unsigned x=0;x<width;++x){
			pixels[(y*width+x)*4]=(x*13+y*3)%256;
			pixels[(y*width+x)*4+1]=(x*2+y*17)%256;
			pixels[(y*width+x)*4+2]=(x*7+y*11)%256;
 pixels[(y*width+x)*4+3]=(x*23+y*31)%256;
		}
		JxlEncoder* encoder=JxlEncoderCreate(nullptr);
		JxlBasicInfo info; JxlEncoderInitBasicInfo(&info);
		info.xsize=width;info.ysize=height;info.num_color_channels=3;info.bits_per_sample=8;info.num_extra_channels=1;info.alpha_bits=8;info.uses_original_profile=id>=4?JXL_TRUE:JXL_FALSE;
		if(JxlEncoderSetBasicInfo(encoder,&info)!=JXL_ENC_SUCCESS)return 1;
		JxlColorEncoding color;JxlColorEncodingSetToSRGB(&color,JXL_FALSE);
		if(JxlEncoderSetColorEncoding(encoder,&color)!=JXL_ENC_SUCCESS)return 2;
		auto* settings=JxlEncoderFrameSettingsCreate(encoder,nullptr);
		if(JxlEncoderSetFrameDistance(settings,1.0f)!=JXL_ENC_SUCCESS)return 3;
		for(auto option:{JXL_ENC_FRAME_SETTING_EPF,JXL_ENC_FRAME_SETTING_GABORISH,JXL_ENC_FRAME_SETTING_PATCHES,JXL_ENC_FRAME_SETTING_NOISE,JXL_ENC_FRAME_SETTING_MODULAR})
			if(JxlEncoderFrameSettingsSetOption(settings,option,0)!=JXL_ENC_SUCCESS)return 4;
		if(JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_EFFORT,5)!=JXL_ENC_SUCCESS)return 5;
				if(id>=8){
			if(JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_GABORISH,1)!=JXL_ENC_SUCCESS)return 11;
			if(JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_EPF,2)!=JXL_ENC_SUCCESS)return 12;
		}
 if(JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_RESAMPLING,color_factors[id])!=JXL_ENC_SUCCESS)return 16;
 if(JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_EXTRA_CHANNEL_RESAMPLING,extra_factors[id])!=JXL_ENC_SUCCESS)return 17;
		if(JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_MODULAR,1)!=JXL_ENC_SUCCESS)return 19;
 JxlPixelFormat format={4,JXL_TYPE_UINT8,JXL_NATIVE_ENDIAN,0};
		if(JxlEncoderAddImageFrame(settings,&format,pixels.data(),pixels.size())!=JXL_ENC_SUCCESS)return 6;
 JxlEncoderCloseInput(encoder);
		std::vector<unsigned char> compressed(1<<20);auto* next=compressed.data();size_t avail=compressed.size();
		if(JxlEncoderProcessOutput(encoder,&next,&avail)!=JXL_ENC_SUCCESS)return 7;
		compressed.resize(compressed.size()-avail);JxlEncoderDestroy(encoder);
		JxlDecoder* decoder=JxlDecoderCreate(nullptr);
		JxlDecoderSubscribeEvents(decoder,JXL_DEC_BASIC_INFO|JXL_DEC_FULL_IMAGE);
		JxlDecoderSetInput(decoder,compressed.data(),compressed.size());JxlDecoderCloseInput(decoder);
		std::vector<unsigned char> output(pixels.size());
		for(;;){auto status=JxlDecoderProcessInput(decoder);if(status==JXL_DEC_SUCCESS)break;
			if(status==JXL_DEC_NEED_IMAGE_OUT_BUFFER){if(JxlDecoderSetImageOutBuffer(decoder,&format,output.data(),output.size())!=JXL_DEC_SUCCESS)return 8;}
			else if(status!=JXL_DEC_BASIC_INFO&&status!=JXL_DEC_FULL_IMAGE)return 9;
		}
		JxlDecoderDestroy(decoder);
		printf("pub const bytes_%u = [_]u8{",id);for(auto byte:compressed)printf("0x%02x,",byte);printf("};\n");
		printf("pub const rgb_%u = [_]u8{",id);for(auto byte:output)printf("%u,",byte);printf("};\n");
	}
}
