// Exact upstream RNG words and actual upstream noise render stages.
#include <cmath>
#include <cstdio>
#include <cstring>
#include <vector>
#define HWY_COMPILE_ONLY_SCALAR
#include "lib/jxl/xorshift128plus-inl.h"
#include "lib/jxl/image_ops.h"
#include "lib/jxl/memory_manager_internal.h"
#include "lib/jxl/render_pipeline/stage_noise.h"
using Rng=jxl::HWY_NAMESPACE::Xorshift128Plus;
jxl::Status Stage(JxlMemoryManager* memory,unsigned id){
 const unsigned widths[]={1,7,16,17,31,33,65,257},heights[]={1,9,3,5,2,17,3,2},groups[]={1,8,16,32,256,16,32,256};
 const unsigned w=widths[id],h=heights[id],g=groups[id];const size_t pad=jxl::kRenderPipelineXOffset;
 JXL_ASSIGN_OR_RETURN(jxl::Image3F raw,jxl::Image3F::Create(memory,w+2*pad,h+4));
 JXL_ASSIGN_OR_RETURN(jxl::Image3F convolved,jxl::Image3F::Create(memory,w+2*pad,h));
 JXL_ASSIGN_OR_RETURN(jxl::Image3F image,jxl::Image3F::Create(memory,w+2*pad,h));
 for(unsigned gy=0;gy<h;gy+=g)for(unsigned gx=0;gx<w;gx+=g){Rng rng(id+1,id*3,gx,gy);const unsigned rw=std::min(g,w-gx),rh=std::min(g,h-gy);
  for(unsigned c=0;c<3;++c)for(unsigned y=0;y<rh;++y)for(unsigned x=0;x<rw;x+=16){uint64_t batch[8];rng.Fill(batch);for(unsigned i=0;i<std::min(16u,rw-x);++i){uint32_t bits=uint32_t(batch[i/2]>>(32*(i%2)));bits=(bits>>9)|0x3f800000;float value;memcpy(&value,&bits,4);raw.PlaneRow(c,gy+y+2)[gx+x+i+pad]=value;}}
 }
 for(unsigned c=0;c<3;++c)for(size_t y=0;y<h+4;++y)for(size_t x=0;x<w+2*pad;++x)if(x<pad||x>=w+pad||y<2||y>=h+2)raw.PlaneRow(c,y)[x]=raw.PlaneRow(c,jxl::Mirror(int64_t(y)-2,h)+2)[jxl::Mirror(int64_t(x)-pad,w)+pad];
 printf("pub const input_%u=[_]i32{",id);for(unsigned c=0;c<3;++c)for(unsigned y=0;y<h;++y)for(unsigned x=0;x<w;++x){const int value=(int((x*37+y*91+c*17)%257)-64)*128;image.PlaneRow(c,y)[x+pad]=value/65536.f;printf("%d,",value);}printf("};\n");
 jxl::NoiseParams params;for(unsigned i=0;i<8;++i)params.lut[i]=id==0?0:((id*31+i*71)%1024)/1024.f;jxl::ColorCorrelation cfl;
 auto conv=jxl::GetConvolveNoiseStage(3);auto add=jxl::GetAddNoiseStage(params,cfl,3);
 for(unsigned y=0;y<h;++y){jxl::RenderPipelineStage::RowInfo in(6),out(6);for(unsigned c=0;c<3;++c){for(int dy=-2;dy<=2;++dy)in[c+3].push_back(raw.PlaneRow(c,y+2+dy));out[c+3].push_back(convolved.PlaneRow(c,y));}JXL_RETURN_IF_ERROR(conv->ProcessRow(in,out,0,w,0,y,0));}
 for(unsigned y=0;y<h;++y){jxl::RenderPipelineStage::RowInfo in(6),out(6);for(unsigned c=0;c<3;++c){in[c].push_back(image.PlaneRow(c,y));in[c+3].push_back(convolved.PlaneRow(c,y));}JXL_RETURN_IF_ERROR(add->ProcessRow(in,out,0,w,0,y,0));}
 printf("pub const output_%u=[_]i32{",id);for(unsigned c=0;c<3;++c)for(unsigned y=0;y<h;++y)for(unsigned x=0;x<w;++x)printf("%d,",int(std::llround(image.PlaneRow(c,y)[x+pad]*(1<<24))));printf("};\n");return true;
}
int main(){
 printf("// Generated by tests/unit/noise_oracle.cc. Inputs 2^16, outputs 2^24.\n");
 const uint32_t seeds[][4]={{0,0,0,0},{1,0,0,0},{0,1,0,0},{0,0,1,0},{0,0,0,1},{0xffffffff,0xffffffff,0xffffffff,0xffffffff},{123,456,256,512},{0x80000000,0x7fffffff,0xff00ff00,0x00ff00ff}};
 printf("pub const seeds=[8][4]u32{");for(auto& seed:seeds){printf(".{");for(auto word:seed)printf("%u,",word);printf("},");}printf("};\npub const random=[8][64]u32{");
 for(auto& seed:seeds){Rng rng(seed[0],seed[1],seed[2],seed[3]);printf(".{");for(unsigned iteration=0;iteration<4;++iteration){uint64_t batch[8];rng.Fill(batch);for(unsigned i=0;i<16;++i)printf("%u,",uint32_t(batch[i/2]>>(32*(i%2)))>>9);}printf("},");}printf("};\n");
 JxlMemoryManager memory;if(!jxl::MemoryManagerInit(&memory,nullptr))return 1;for(unsigned id=0;id<8;++id)if(!Stage(&memory,id))return 2;
}
