#include <jxl/decode.h>
#include <jxl/encode.h>
#include <jxl/color_encoding.h>
#include <cstdio>
#include <vector>

#define CHECK(expr) do { if (!(expr)) { fprintf(stderr, "crop oracle failed at line %d\n", __LINE__); return 1; } } while (0)

int main() {
	const JxlPixelFormat format = { 3, JXL_TYPE_UINT8, JXL_NATIVE_ENDIAN, 0 };
	printf("// Generated by tests/unit/orientation_crop_oracle.cc against upstream libjxl.\n");
	for (unsigned orientation = 1; orientation <= 8; ++orientation) {
		for (unsigned negative = 0; negative <= 1; ++negative) {
			auto *encoder = JxlEncoderCreate(nullptr);
			CHECK(encoder);
			JxlBasicInfo info;
			JxlEncoderInitBasicInfo(&info);
			info.xsize = 5; info.ysize = 4; info.bits_per_sample = 8;
			info.num_color_channels = 3; info.uses_original_profile = JXL_TRUE;
			info.orientation = static_cast<JxlOrientation>(orientation);
			CHECK(JxlEncoderSetBasicInfo(encoder, &info) == JXL_ENC_SUCCESS);
			JxlColorEncoding color;
			JxlColorEncodingSetToSRGB(&color, JXL_FALSE);
			CHECK(JxlEncoderSetColorEncoding(encoder, &color) == JXL_ENC_SUCCESS);
			for (unsigned index = 0; index < 2; ++index) {
				auto *settings = JxlEncoderFrameSettingsCreate(encoder, nullptr);
				CHECK(JxlEncoderSetFrameLossless(settings, JXL_TRUE) == JXL_ENC_SUCCESS);
				JxlFrameHeader frame;
				JxlEncoderInitFrameHeader(&frame);
				frame.layer_info.have_crop = index != 0;
				frame.layer_info.xsize = index ? 3 : 5;
				frame.layer_info.ysize = index ? 2 : 4;
				frame.layer_info.crop_x0 = index ? (negative ? -1 : 1) : 0;
				frame.layer_info.crop_y0 = index ? (negative ? -2 : 1) : 0;
				frame.layer_info.save_as_reference = index ? 0 : 1;
				CHECK(JxlEncoderSetFrameHeader(settings, &frame) == JXL_ENC_SUCCESS);
				std::vector<unsigned char> pixels(frame.layer_info.xsize * frame.layer_info.ysize * 3);
				for (size_t i = 0; i < pixels.size(); ++i) pixels[i] = (i * 13 + index * 7) % 251;
				CHECK(JxlEncoderAddImageFrame(settings, &format, pixels.data(), pixels.size()) == JXL_ENC_SUCCESS);
			}
			JxlEncoderCloseInput(encoder);
			std::vector<unsigned char> bytes(4096);
			unsigned char *next = bytes.data();
			size_t available = bytes.size();
			CHECK(JxlEncoderProcessOutput(encoder, &next, &available) == JXL_ENC_SUCCESS);
			bytes.resize(bytes.size() - available);
			JxlEncoderDestroy(encoder);
			printf("pub const bytes_%u_%u = [_]u8{", orientation, negative);
			for (auto byte : bytes) printf("%u,", byte);
			printf("};\n");
			for (unsigned keep = 0; keep <= 1; ++keep) {
				auto *decoder = JxlDecoderCreate(nullptr);
				CHECK(decoder);
				CHECK(JxlDecoderSetKeepOrientation(decoder, keep) == JXL_DEC_SUCCESS);
				CHECK(JxlDecoderSetCoalescing(decoder, JXL_FALSE) == JXL_DEC_SUCCESS);
				CHECK(JxlDecoderSubscribeEvents(decoder, JXL_DEC_FRAME | JXL_DEC_FULL_IMAGE) == JXL_DEC_SUCCESS);
				CHECK(JxlDecoderSetInput(decoder, bytes.data(), bytes.size()) == JXL_DEC_SUCCESS);
				JxlDecoderCloseInput(decoder);
				for (unsigned index = 0; index < 2; ++index) {
					CHECK(JxlDecoderProcessInput(decoder) == JXL_DEC_FRAME);
					JxlFrameHeader frame;
					CHECK(JxlDecoderGetFrameHeader(decoder, &frame) == JXL_DEC_SUCCESS);
					printf("pub const header_%u_%u_%u_%u = [_]i32{%u,%u,%d,%d,%d};\n", orientation, negative, keep, index, frame.layer_info.xsize, frame.layer_info.ysize, frame.layer_info.have_crop, frame.layer_info.crop_x0, frame.layer_info.crop_y0);
					CHECK(JxlDecoderProcessInput(decoder) == JXL_DEC_NEED_IMAGE_OUT_BUFFER);
					size_t size = 0;
					CHECK(JxlDecoderImageOutBufferSize(decoder, &format, &size) == JXL_DEC_SUCCESS);
					std::vector<unsigned char> pixels(size);
					CHECK(JxlDecoderSetImageOutBuffer(decoder, &format, pixels.data(), pixels.size()) == JXL_DEC_SUCCESS);
					CHECK(JxlDecoderProcessInput(decoder) == JXL_DEC_FULL_IMAGE);
					printf("pub const pixels_%u_%u_%u_%u = [_]u8{", orientation, negative, keep, index);
					for (auto pixel : pixels) printf("%u,", pixel);
					printf("};\n");
				}
				CHECK(JxlDecoderProcessInput(decoder) == JXL_DEC_SUCCESS);
				JxlDecoderDestroy(decoder);
			}
		}
	}
}
