#include <jxl/decode.h>
#include <jxl/encode.h>
#include <jxl/color_encoding.h>
#include <cstdio>
#include <vector>
#include "lib/jxl/dec_bit_reader.h"
#include "lib/jxl/enc_fields.h"
#include "lib/jxl/enc_aux_out.h"
#include "lib/jxl/image_metadata.h"
#include "lib/jxl/memory_manager_internal.h"

#define CHECK(expr) do { if (!(expr)) { fprintf(stderr, "orientation oracle failed at line %d\n", __LINE__); return 1; } } while (0)

static bool with_preview(const std::vector<unsigned char>& bytes, std::vector<unsigned char>& output) {
	JxlMemoryManager memory;
	if (!jxl::MemoryManagerInit(&memory, nullptr)) return false;
	jxl::BitReader reader(bytes);
	if (reader.ReadBits(16) != 0x0aff) return false;
	jxl::CodecMetadata metadata;
	if (!jxl::ReadSizeHeader(&reader, &metadata.size) || !jxl::ReadImageMetadata(&reader, &metadata.m)) return false;
	metadata.transform_data.nonserialized_xyb_encoded = metadata.m.xyb_encoded;
	if (!jxl::Bundle::Read(&reader, &metadata.transform_data) || !reader.JumpToByteBoundary()) return false;
	const size_t offset = reader.TotalBitsConsumed() / 8;
	if (!reader.Close()) return false;
	metadata.m.have_preview = true;
	if (!metadata.m.preview_size.Set(3, 2)) return false;
	jxl::BitWriter writer(&memory);
	if (!jxl::WriteCodestreamHeaders(&metadata, &writer, nullptr)) return false;
	writer.ZeroPadToByte();
	auto header = writer.GetSpan();
	output.assign(header.begin(), header.end());
	output.insert(output.end(), bytes.begin() + offset, bytes.end());
	output.insert(output.end(), bytes.begin() + offset, bytes.end());
	return true;
}

int main() {
	const unsigned char pixels[] = { 3, 17, 29, 41, 53, 67, 79, 83, 97, 109, 127, 139, 151, 167, 179, 191, 211, 239 };
	const JxlPixelFormat format = { 3, JXL_TYPE_UINT8, JXL_NATIVE_ENDIAN, 0 };
	printf("// Generated by tests/unit/orientation_oracle.cc against upstream libjxl.\n");
	for (unsigned orientation = 1; orientation <= 8; ++orientation) {
		JxlEncoder *encoder = JxlEncoderCreate(nullptr);
		CHECK(encoder);
		JxlBasicInfo info;
		JxlEncoderInitBasicInfo(&info);
		info.xsize = 3;
		info.ysize = 2;
		info.bits_per_sample = 8;
		info.num_color_channels = 3;
		info.uses_original_profile = JXL_TRUE;
		info.orientation = static_cast<JxlOrientation>(orientation);
		CHECK(JxlEncoderSetBasicInfo(encoder, &info) == JXL_ENC_SUCCESS);
		JxlColorEncoding color;
		JxlColorEncodingSetToSRGB(&color, JXL_FALSE);
		CHECK(JxlEncoderSetColorEncoding(encoder, &color) == JXL_ENC_SUCCESS);
		auto *settings = JxlEncoderFrameSettingsCreate(encoder, nullptr);
		CHECK(JxlEncoderSetFrameLossless(settings, JXL_TRUE) == JXL_ENC_SUCCESS);
		CHECK(JxlEncoderAddImageFrame(settings, &format, pixels, sizeof(pixels)) == JXL_ENC_SUCCESS);
		JxlEncoderCloseInput(encoder);
		std::vector<unsigned char> bytes(4096);
		unsigned char *next = bytes.data();
		size_t available = bytes.size();
		CHECK(JxlEncoderProcessOutput(encoder, &next, &available) == JXL_ENC_SUCCESS);
		bytes.resize(bytes.size() - available);
		JxlEncoderDestroy(encoder);
		printf("pub const bytes_%u = [_]u8{", orientation);
		for (auto byte : bytes) printf("%u,", byte);
		printf("};\n");
		std::vector<unsigned char> preview_bytes;
		CHECK(with_preview(bytes, preview_bytes));
		printf("pub const preview_bytes_%u = [_]u8{", orientation);
		for (auto byte : preview_bytes) printf("%u,", byte);
		printf("};\n");
		for (unsigned keep = 0; keep <= 1; ++keep) {
			auto *decoder = JxlDecoderCreate(nullptr);
			CHECK(decoder);
			CHECK(JxlDecoderSetKeepOrientation(decoder, keep) == JXL_DEC_SUCCESS);
			CHECK(JxlDecoderSubscribeEvents(decoder, JXL_DEC_BASIC_INFO | JXL_DEC_FRAME | JXL_DEC_FULL_IMAGE) == JXL_DEC_SUCCESS);
			CHECK(JxlDecoderSetInput(decoder, bytes.data(), bytes.size()) == JXL_DEC_SUCCESS);
			JxlDecoderCloseInput(decoder);
			CHECK(JxlDecoderProcessInput(decoder) == JXL_DEC_BASIC_INFO);
			CHECK(JxlDecoderGetBasicInfo(decoder, &info) == JXL_DEC_SUCCESS);
			printf("pub const info_%u_%u = [_]u32{%u,%u,%u};\n", orientation, keep, info.xsize, info.ysize, unsigned(info.orientation));
			CHECK(JxlDecoderProcessInput(decoder) == JXL_DEC_FRAME);
			JxlFrameHeader frame;
			CHECK(JxlDecoderGetFrameHeader(decoder, &frame) == JXL_DEC_SUCCESS);
			printf("pub const frame_%u_%u = [_]u32{%u,%u};\n", orientation, keep, frame.layer_info.xsize, frame.layer_info.ysize);
			CHECK(JxlDecoderProcessInput(decoder) == JXL_DEC_NEED_IMAGE_OUT_BUFFER);
			size_t size = 0;
			CHECK(JxlDecoderImageOutBufferSize(decoder, &format, &size) == JXL_DEC_SUCCESS);
			CHECK(size == sizeof(pixels));
			std::vector<unsigned char> output(size);
			CHECK(JxlDecoderSetImageOutBuffer(decoder, &format, output.data(), output.size()) == JXL_DEC_SUCCESS);
			CHECK(JxlDecoderProcessInput(decoder) == JXL_DEC_FULL_IMAGE);
			CHECK(JxlDecoderProcessInput(decoder) == JXL_DEC_SUCCESS);
			printf("pub const pixels_%u_%u = [_]u8{", orientation, keep);
			for (auto byte : output) printf("%u,", byte);
			printf("};\n");
			JxlDecoderRewind(decoder);
			CHECK(JxlDecoderSetInput(decoder, bytes.data(), bytes.size()) == JXL_DEC_SUCCESS);
			JxlDecoderCloseInput(decoder);
			CHECK(JxlDecoderProcessInput(decoder) == JXL_DEC_BASIC_INFO);
			CHECK(JxlDecoderProcessInput(decoder) == JXL_DEC_FRAME);
			CHECK(JxlDecoderProcessInput(decoder) == JXL_DEC_NEED_IMAGE_OUT_BUFFER);
			JxlPixelFormat aligned = format;
			aligned.align = 8;
			CHECK(JxlDecoderImageOutBufferSize(decoder, &aligned, &size) == JXL_DEC_SUCCESS);
			output.assign(size, 0xa5);
			CHECK(JxlDecoderSetImageOutBuffer(decoder, &aligned, output.data(), output.size()) == JXL_DEC_SUCCESS);
			CHECK(JxlDecoderProcessInput(decoder) == JXL_DEC_FULL_IMAGE);
			CHECK(JxlDecoderProcessInput(decoder) == JXL_DEC_SUCCESS);
			printf("pub const aligned_%u_%u = [_]u8{", orientation, keep);
			for (auto byte : output) printf("%u,", byte);
			printf("};\n");
			JxlDecoderDestroy(decoder);
			decoder = JxlDecoderCreate(nullptr);
			CHECK(decoder);
			CHECK(JxlDecoderSetKeepOrientation(decoder, keep) == JXL_DEC_SUCCESS);
			CHECK(JxlDecoderSubscribeEvents(decoder, JXL_DEC_PREVIEW_IMAGE | JXL_DEC_FULL_IMAGE) == JXL_DEC_SUCCESS);
			CHECK(JxlDecoderSetInput(decoder, preview_bytes.data(), preview_bytes.size()) == JXL_DEC_SUCCESS);
			JxlDecoderCloseInput(decoder);
			CHECK(JxlDecoderProcessInput(decoder) == JXL_DEC_NEED_PREVIEW_OUT_BUFFER);
			CHECK(JxlDecoderPreviewOutBufferSize(decoder, &aligned, &size) == JXL_DEC_SUCCESS);
			output.assign(size, 0xa5);
			CHECK(JxlDecoderSetPreviewOutBuffer(decoder, &aligned, output.data(), output.size()) == JXL_DEC_SUCCESS);
			CHECK(JxlDecoderProcessInput(decoder) == JXL_DEC_PREVIEW_IMAGE);
			printf("pub const preview_pixels_%u_%u = [_]u8{", orientation, keep);
			for (auto byte : output) printf("%u,", byte);
			printf("};\n");
			CHECK(JxlDecoderProcessInput(decoder) == JXL_DEC_NEED_IMAGE_OUT_BUFFER);
			CHECK(JxlDecoderSetImageOutBuffer(decoder, &aligned, output.data(), output.size()) == JXL_DEC_SUCCESS);
			CHECK(JxlDecoderProcessInput(decoder) == JXL_DEC_FULL_IMAGE);
			CHECK(JxlDecoderProcessInput(decoder) == JXL_DEC_SUCCESS);
			JxlDecoderDestroy(decoder);
			decoder = JxlDecoderCreate(nullptr);
			CHECK(decoder);
			CHECK(JxlDecoderSetKeepOrientation(decoder, keep) == JXL_DEC_SUCCESS);
			CHECK(JxlDecoderSetCoalescing(decoder, JXL_FALSE) == JXL_DEC_SUCCESS);
			CHECK(JxlDecoderSubscribeEvents(decoder, JXL_DEC_FRAME) == JXL_DEC_SUCCESS);
			CHECK(JxlDecoderSetInput(decoder, bytes.data(), bytes.size()) == JXL_DEC_SUCCESS);
			JxlDecoderCloseInput(decoder);
			CHECK(JxlDecoderProcessInput(decoder) == JXL_DEC_FRAME);
			CHECK(JxlDecoderGetFrameHeader(decoder, &frame) == JXL_DEC_SUCCESS);
			printf("pub const layer_%u_%u = [_]u32{%u,%u};\n", orientation, keep, frame.layer_info.xsize, frame.layer_info.ysize);
			JxlDecoderDestroy(decoder);
			decoder = JxlDecoderCreate(nullptr);
			CHECK(decoder);
			CHECK(JxlDecoderSetKeepOrientation(decoder, keep) == JXL_DEC_SUCCESS);
			CHECK(JxlDecoderSubscribeEvents(decoder, JXL_DEC_FULL_IMAGE) == JXL_DEC_SUCCESS);
			CHECK(JxlDecoderSetInput(decoder, bytes.data(), bytes.size()) == JXL_DEC_SUCCESS);
			JxlDecoderCloseInput(decoder);
			CHECK(JxlDecoderProcessInput(decoder) == JXL_DEC_NEED_IMAGE_OUT_BUFFER);
			const JxlPixelFormat wide = { 4, JXL_TYPE_UINT16, JXL_BIG_ENDIAN, 16 };
			CHECK(JxlDecoderImageOutBufferSize(decoder, &wide, &size) == JXL_DEC_SUCCESS);
			output.assign(size, 0xa5);
			CHECK(JxlDecoderSetImageOutBuffer(decoder, &wide, output.data(), output.size()) == JXL_DEC_SUCCESS);
			CHECK(JxlDecoderProcessInput(decoder) == JXL_DEC_FULL_IMAGE);
			CHECK(JxlDecoderProcessInput(decoder) == JXL_DEC_SUCCESS);
			printf("pub const wide_%u_%u = [_]u8{", orientation, keep);
			for (auto byte : output) printf("%u,", byte);
			printf("};\n");
			JxlDecoderDestroy(decoder);
		}
	}
}
