// Encode, decode and apply dictionaries with the retained upstream library.
#include <cstdio>
#include <cmath>
#include "lib/jxl/enc_patch_dictionary.h"
#include "lib/jxl/enc_aux_out.h"
#include "lib/jxl/memory_manager_internal.h"
jxl::Status Generate(JxlMemoryManager* memory,unsigned id){
 const unsigned extras=id/8,channels=3+extras,width=16,height=12;
 jxl::ImageMetadata metadata;
 metadata.extra_channel_info.resize(extras);
 for(unsigned e=0;e<extras;++e){metadata.extra_channel_info[e].type=extras==2&&e==0?jxl::ExtraChannel::kDepth:jxl::ExtraChannel::kAlpha;metadata.extra_channel_info[e].alpha_associated=id%2;}
 std::array<jxl::ReferenceFrame,4> refs;
 for(unsigned r=0;r<4;++r){
  refs[r].frame=std::make_unique<jxl::ImageBundle>(memory,&metadata);refs[r].ib_is_in_xyb=true;
  JXL_ASSIGN_OR_RETURN(jxl::Image3F image,jxl::Image3F::Create(memory,8,6));
  for(unsigned c=0;c<3;++c)for(unsigned y=0;y<6;++y)for(unsigned x=0;x<8;++x)image.PlaneRow(c,y)[x]=(int((x*3+y*7+c*5+r*11)%19)-4)/8.f;
  JXL_RETURN_IF_ERROR(refs[r].frame->SetFromImage(std::move(image),jxl::ColorEncoding::SRGB()));
  std::vector<jxl::ImageF> ec;
  for(unsigned e=0;e<extras;++e){JXL_ASSIGN_OR_RETURN(jxl::ImageF plane,jxl::ImageF::Create(memory,8,6));for(unsigned y=0;y<6;++y)for(unsigned x=0;x<8;++x)plane.Row(y)[x]=(int((x*3+y*7+(3+e)*5+r*11)%19)-4)/8.f;ec.push_back(std::move(plane));}
  JXL_RETURN_IF_ERROR(refs[r].frame->SetExtraChannels(std::move(ec)));
 }
 std::vector<jxl::PatchReferencePosition> crops={{id%4,1,2,3,2},{(id+1)%4,0,0,4,3}};
 std::vector<jxl::PatchPosition> positions={{5,4,0},{2,2,0},{3,3,0},{1,1,1},{12,9,1}};
 std::vector<jxl::PatchBlending> blend;
 for(unsigned p=0;p<positions.size();++p)for(unsigned c=0;c<=extras;++c)blend.push_back({static_cast<jxl::PatchBlendMode>((id+c)%8),extras==2?1u:0u,p%2!=0});
 jxl::PatchDictionary encoded(memory);encoded.SetShared(&refs);
 jxl::PatchDictionaryEncoder::SetPositions(&encoded,std::move(positions),std::move(crops),std::move(blend),extras+1);
 jxl::BitWriter writer(memory);JXL_RETURN_IF_ERROR(jxl::PatchDictionaryEncoder::Encode(encoded,&writer,jxl::LayerType::Dictionary,nullptr));
 const size_t bits=writer.BitsWritten();writer.ZeroPadToByte();auto bytes=writer.GetSpan();
 printf("pub const bytes_%u=[_]u8{",id);for(auto byte:bytes)printf("%u,",byte);printf("};\npub const bits_%u:usize=%zu;\n",id,bits);
 jxl::BitReader reader(bytes);jxl::PatchDictionary decoded(memory);decoded.SetShared(&refs);bool uses=false;JXL_RETURN_IF_ERROR(decoded.Decode(memory,&reader,width,height,extras,&uses));JXL_RETURN_IF_ERROR(reader.Close());
 printf("pub const refs_%u:u8=%u;\npub const uses_%u:bool=%s;\n",id,decoded.GetReferences(),id,uses?"true":"false");
 JXL_ASSIGN_OR_RETURN(jxl::ImageF output,jxl::ImageF::Create(memory,width,height*channels));
 std::vector<float*> rows(channels);
 for(unsigned y=0;y<height;++y){for(unsigned c=0;c<channels;++c){rows[c]=output.Row(c*height+y);for(unsigned x=0;x<width;++x)rows[c][x]=(int((x*5+y*3+c*7)%17)-3)/8.f;}JXL_RETURN_IF_ERROR(decoded.AddOneRow(rows.data(),y,0,width,metadata.extra_channel_info));}
 printf("pub const pixels_%u=[_]i32{",id);for(unsigned c=0;c<channels;++c)for(unsigned y=0;y<height;++y)for(unsigned x=0;x<width;++x)printf("%d,",int(std::llround(output.ConstRow(c*height+y)[x]*(1<<16))));printf("};\n");
 return true;
}
int main(){JxlMemoryManager memory;if(!jxl::MemoryManagerInit(&memory,nullptr))return 1;printf("// Generated by tests/unit/patches_oracle.cc. Pixels scaled by 2^16.\n");for(unsigned id=0;id<24;++id)if(!Generate(&memory,id))return 2;}
