// Complete structured-primary images and public output profiles from upstream.
#include <cstdio>
#include <cstring>
#include <vector>
#include "jxl/encode.h"
#include "jxl/decode.h"
#include "lib/jxl/fields.h"
#include "lib/jxl/frame_header.h"
#include "lib/jxl/enc_fields.h"
#include "lib/jxl/memory_manager_internal.h"
static void Coordinates(const JxlColorEncoding& color,unsigned id,const char* name){
 printf("pub const %s_%u=[_]f64{",name,id);
 for(double value:color.white_point_xy)printf("%.17e,",value);
 for(double value:color.primaries_red_xy)printf("%.17e,",value);
 for(double value:color.primaries_green_xy)printf("%.17e,",value);
 for(double value:color.primaries_blue_xy)printf("%.17e,",value);
 printf("};\n");
}
int main(){
 printf("// Generated by tests/unit/primary_frame_oracle.cc.\n");
 const JxlPrimaries ps[]={JXL_PRIMARIES_SRGB,JXL_PRIMARIES_P3,JXL_PRIMARIES_2100,JXL_PRIMARIES_CUSTOM};
 const JxlWhitePoint ws[]={JXL_WHITE_POINT_D65,JXL_WHITE_POINT_E,JXL_WHITE_POINT_DCI,JXL_WHITE_POINT_CUSTOM};
 for(unsigned id=0;id<50;++id){
  const bool gray=id>=32&&id<40,modular=id%2;
  const unsigned channels=gray?1:3,width=19,height=13;
  const unsigned p=id>=40?1+(id-40)/4:gray?0:id/8,w=id>=40?(id>=44?2:0):(id/2)%4;
  JxlColorEncoding color;JxlColorEncodingSetToLinearSRGB(&color,gray);
  if(gray)color.transfer_function=JXL_TRANSFER_FUNCTION_SRGB;
  if(id>=40)color.transfer_function=((id-40)/2)%2?JXL_TRANSFER_FUNCTION_HLG:JXL_TRANSFER_FUNCTION_PQ;
  color.primaries=ps[p];color.white_point=ws[w];color.white_point_xy[0]=0.321;color.white_point_xy[1]=0.345;
  color.primaries_red_xy[0]=0.67;color.primaries_red_xy[1]=0.33;color.primaries_green_xy[0]=0.21;color.primaries_green_xy[1]=0.71;color.primaries_blue_xy[0]=0.14;color.primaries_blue_xy[1]=0.08;
  if(id>=48){color.primaries=JXL_PRIMARIES_CUSTOM;color.white_point=JXL_WHITE_POINT_CUSTOM;color.transfer_function=JXL_TRANSFER_FUNCTION_LINEAR;color.white_point_xy[0]=0.32168;color.white_point_xy[1]=0.33767;color.primaries_red_xy[0]=0.7347;color.primaries_red_xy[1]=0.2653;color.primaries_green_xy[0]=0.000001;color.primaries_green_xy[1]=1;color.primaries_blue_xy[0]=0.0001;color.primaries_blue_xy[1]=-0.077;}
  auto* enc=JxlEncoderCreate(nullptr);JxlBasicInfo info;JxlEncoderInitBasicInfo(&info);
  info.xsize=width;info.ysize=height;info.num_color_channels=channels;info.bits_per_sample=8;info.uses_original_profile=JXL_FALSE;info.intensity_target=modular?1000.f:255.f;
  if(JxlEncoderSetBasicInfo(enc,&info)!=JXL_ENC_SUCCESS||JxlEncoderSetColorEncoding(enc,&color)!=JXL_ENC_SUCCESS){fprintf(stderr,"color rejected id=%u\n",id);return 1;}
  auto* settings=JxlEncoderFrameSettingsCreate(enc,nullptr);
  if(JxlEncoderSetFrameDistance(settings,1.f)!=JXL_ENC_SUCCESS||JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_MODULAR,modular)!=JXL_ENC_SUCCESS||JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_EPF,0)!=JXL_ENC_SUCCESS||JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_GABORISH,0)!=JXL_ENC_SUCCESS||JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_PATCHES,0)!=JXL_ENC_SUCCESS||JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_NOISE,0)!=JXL_ENC_SUCCESS)return 2;
  std::vector<unsigned char> input(width*height*channels);for(unsigned y=0;y<height;++y)for(unsigned x=0;x<width;++x)for(unsigned c=0;c<channels;++c)input[(y*width+x)*channels+c]=(x*13+y*17+c*31)%256;
  JxlPixelFormat format={channels,JXL_TYPE_UINT8,JXL_NATIVE_ENDIAN,0};if(JxlEncoderAddImageFrame(settings,&format,input.data(),input.size())!=JXL_ENC_SUCCESS)return 3;
  JxlEncoderCloseInput(enc);std::vector<unsigned char> bytes(1<<20);auto* next=bytes.data();size_t avail=bytes.size();if(JxlEncoderProcessOutput(enc,&next,&avail)!=JXL_ENC_SUCCESS)return 4;bytes.resize(bytes.size()-avail);JxlEncoderDestroy(enc);
  jxl::CodecMetadata metadata;jxl::BitReader reader(bytes);
  if(reader.ReadBits(16)!=0x0aff||!jxl::ReadSizeHeader(&reader,&metadata.size)||!jxl::ReadImageMetadata(&reader,&metadata.m)||metadata.m.color_encoding.WantICC())return 5;
  metadata.transform_data.nonserialized_xyb_encoded=metadata.m.xyb_encoded;
  if(!jxl::Bundle::Read(&reader,&metadata.transform_data)||!reader.JumpToByteBoundary())return 6;
  const size_t start=reader.TotalBitsConsumed()/8;jxl::FrameHeader header(&metadata);
  if(!jxl::ReadFrameHeader(&reader,&header)||!reader.Close()||header.encoding!=(modular?jxl::FrameEncoding::kModular:jxl::FrameEncoding::kVarDCT)||header.loop_filter.gab||header.loop_filter.epf_iters||!metadata.m.xyb_encoded)return 7;
  printf("pub const bytes_%u=[_]u8{",id);for(auto b:bytes)printf("%u,",b);printf("};\n");
  for(unsigned kind=0;kind<3;++kind){
   auto* dec=JxlDecoderCreate(nullptr);JxlDecoderSubscribeEvents(dec,JXL_DEC_COLOR_ENCODING|JXL_DEC_FULL_IMAGE);JxlDecoderSetInput(dec,bytes.data(),bytes.size());JxlDecoderCloseInput(dec);
   format.data_type=kind?JXL_TYPE_FLOAT:JXL_TYPE_UINT8;std::vector<unsigned char> output(input.size()*(kind?4:1));unsigned frames=0;
   for(;;){const auto status=JxlDecoderProcessInput(dec);if(status==JXL_DEC_SUCCESS)break;
    if(status==JXL_DEC_COLOR_ENCODING){
     JxlColorEncoding original,actual;
     if(JxlDecoderGetColorAsEncodedProfile(dec,JXL_COLOR_PROFILE_TARGET_ORIGINAL,&original)!=JXL_DEC_SUCCESS||JxlDecoderGetColorAsEncodedProfile(dec,JXL_COLOR_PROFILE_TARGET_DATA,&actual)!=JXL_DEC_SUCCESS)return 8;
     if(original.white_point!=color.white_point||(!gray&&original.primaries!=color.primaries)||actual.transfer_function!=(gray&&w?JXL_TRANSFER_FUNCTION_LINEAR:color.transfer_function))return 9;
     if(kind==0){Coordinates(original,id,"original_xy");Coordinates(actual,id,"data_xy");printf("pub const data_enums_%u=[_]u32{%u,%u,%u,%u,};\n",id,unsigned(actual.color_space),unsigned(actual.white_point),unsigned(actual.primaries),unsigned(actual.transfer_function));}
     if(kind==2){actual.transfer_function=JXL_TRANSFER_FUNCTION_LINEAR;if(JxlDecoderSetPreferredColorProfile(dec,&actual)!=JXL_DEC_SUCCESS)return 10;}
    }else if(status==JXL_DEC_NEED_IMAGE_OUT_BUFFER){if(JxlDecoderSetImageOutBuffer(dec,&format,output.data(),output.size())!=JXL_DEC_SUCCESS)return 11;}else if(status==JXL_DEC_FULL_IMAGE)++frames;else{fprintf(stderr,"decode id=%u status=%d\n",id,status);return 12;}
   }
   JxlDecoderDestroy(dec);if(frames!=1)return 13;
   printf("pub const %s_%u=[_]%s{",kind==2?"linear_bits":kind?"float_bits":"pixels",id,kind?"u32":"u8");
   for(size_t i=0;i<output.size();i+=kind?4:1){if(kind){uint32_t bits;memcpy(&bits,output.data()+i,4);printf("0x%08x,",bits);}else printf("%u,",output[i]);}printf("};\n");
  }
 }
}
