// Raw quant table wire payloads encoded by upstream modular machinery.
#include <cstdio>
#include <vector>
#include "lib/jxl/enc_aux_out.h"
#include "lib/jxl/enc_modular.h"
#include "lib/jxl/enc_bit_writer.h"
#include "lib/jxl/quant_weights.h"
#include "lib/jxl/enc_quant_weights.h"
#include "lib/jxl/memory_manager_internal.h"
jxl::Status Generate(JxlMemoryManager* memory, size_t id) {
 const size_t table=id<17?id:0;
 const size_t width=8*jxl::DequantMatrices::required_size_x[table];
 const size_t height=8*jxl::DequantMatrices::required_size_y[table];
 std::vector<int> samples(3*width*height);
 for(size_t i=0;i<samples.size();++i)samples[i]=1+(i*13+i/width*7)%251;
 if(id==17)samples[17]=0;
 if(id==18)samples[19]=-3;
 auto quant=jxl::QuantEncoding::RAW(std::move(samples),0);
 quant.qraw.qtable_den=id==19?0.f:id==20?-1.f:0.125f;
 jxl::BitWriter writer(memory);
 JXL_RETURN_IF_ERROR(writer.WithMaxBits(1<<25,jxl::LayerType::Header,nullptr,[&]{return jxl::ModularFrameEncoder::EncodeQuantTable(memory,width,height,&writer,quant,table,nullptr);}));
 const auto bits=writer.BitsWritten();writer.ZeroPadToByte();
 printf("pub const width_%zu:usize=%zu; pub const height_%zu:usize=%zu; pub const bits_%zu:usize=%zu;\n",id,width,id,height,id,bits);
 printf("pub const bytes_%zu=[_]u8{",id);for(auto byte:writer.GetSpan())printf("0x%02x,",byte);printf("};\n");
 return true;
}
int main(){JxlMemoryManager memory;if(!jxl::MemoryManagerInit(&memory,nullptr))return 1;
 printf("// Generated by tests/unit/raw_quant_oracle.cc with upstream libjxl.\n");
 for(size_t id=0;id<21;++id)if(!Generate(&memory,id))return 2;
 std::vector<jxl::QuantEncoding> encodings;
 for(size_t table=0;table<17;++table){
  const size_t width=8*jxl::DequantMatrices::required_size_x[table], height=8*jxl::DequantMatrices::required_size_y[table];
  std::vector<int> values(3*width*height);for(size_t i=0;i<values.size();++i)values[i]=1+(i*13+i/width*7)%251;
  auto quant=jxl::QuantEncoding::RAW(std::move(values));quant.qraw.qtable_den=0.125f;encodings.push_back(std::move(quant));
 }
 jxl::DequantMatrices matrices;matrices.SetEncodings(encodings);jxl::BitWriter writer(&memory);
 if(!jxl::DequantMatricesEncode(&memory,matrices,&writer,jxl::LayerType::Header,nullptr))return 3;
 printf("pub const bits_all:usize=%zu;\n",writer.BitsWritten());writer.ZeroPadToByte();
 printf("pub const bytes_all=[_]u8{");for(auto byte:writer.GetSpan())printf("0x%02x,",byte);printf("};\n");
}
