// Full-image reference for structured transfer functions in XYB output.
#include <cstdio>
#include <cstring>
#include <vector>
#include "jxl/encode.h"
#include "jxl/decode.h"
#include "jxl/color_encoding.h"
#include "lib/jxl/fields.h"
#include "lib/jxl/frame_header.h"
#include "lib/jxl/cms/transfer_functions.h"
int main(){
 printf("// Generated by tests/unit/transfer_frame_oracle.cc.\n");
 const JxlTransferFunction tfs[]={JXL_TRANSFER_FUNCTION_709,JXL_TRANSFER_FUNCTION_LINEAR,JXL_TRANSFER_FUNCTION_SRGB,JXL_TRANSFER_FUNCTION_PQ,JXL_TRANSFER_FUNCTION_DCI,JXL_TRANSFER_FUNCTION_HLG,JXL_TRANSFER_FUNCTION_GAMMA};
 for(unsigned id=0;id<28;++id){
  const bool gray=id>=14,modular=id%2;const unsigned channels=gray?1:3,width=17,height=11,kind=(id%14)/2;
  auto* enc=JxlEncoderCreate(nullptr);JxlBasicInfo info;JxlEncoderInitBasicInfo(&info);info.xsize=width;info.ysize=height;info.num_color_channels=channels;info.bits_per_sample=8;info.uses_original_profile=JXL_FALSE;info.intensity_target=modular?1000.f:255.f;
  if(JxlEncoderSetBasicInfo(enc,&info)!=JXL_ENC_SUCCESS)return 1;
  JxlColorEncoding color;JxlColorEncodingSetToSRGB(&color,gray);color.transfer_function=tfs[kind];color.gamma=0.45;
  if(JxlEncoderSetColorEncoding(enc,&color)!=JXL_ENC_SUCCESS)return 2;
  auto* settings=JxlEncoderFrameSettingsCreate(enc,nullptr);
  if(JxlEncoderSetFrameDistance(settings,1.f)!=JXL_ENC_SUCCESS||JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_MODULAR,modular)!=JXL_ENC_SUCCESS||JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_EPF,0)!=JXL_ENC_SUCCESS||JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_GABORISH,0)!=JXL_ENC_SUCCESS||JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_PATCHES,0)!=JXL_ENC_SUCCESS||JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_NOISE,0)!=JXL_ENC_SUCCESS)return 3;
  std::vector<unsigned char> input(width*height*channels);for(unsigned y=0;y<height;++y)for(unsigned x=0;x<width;++x)for(unsigned c=0;c<channels;++c)input[(y*width+x)*channels+c]=(x*13+y*17+c*31)%256;
  JxlPixelFormat format={channels,JXL_TYPE_UINT8,JXL_NATIVE_ENDIAN,0};if(JxlEncoderAddImageFrame(settings,&format,input.data(),input.size())!=JXL_ENC_SUCCESS)return 4;JxlEncoderCloseInput(enc);std::vector<unsigned char> bytes(1<<20);auto* next=bytes.data();size_t avail=bytes.size();if(JxlEncoderProcessOutput(enc,&next,&avail)!=JXL_ENC_SUCCESS)return 5;bytes.resize(bytes.size()-avail);JxlEncoderDestroy(enc);
  jxl::CodecMetadata metadata;jxl::BitReader reader(bytes);if(reader.ReadBits(16)!=0x0aff||!jxl::ReadSizeHeader(&reader,&metadata.size)||!jxl::ReadImageMetadata(&reader,&metadata.m))return 6;
  metadata.transform_data.nonserialized_xyb_encoded=metadata.m.xyb_encoded;if(!jxl::Bundle::Read(&reader,&metadata.transform_data)||!reader.JumpToByteBoundary())return 7;
  jxl::FrameHeader header(&metadata);if(!jxl::ReadFrameHeader(&reader,&header)||!reader.Close()||header.encoding!=(modular?jxl::FrameEncoding::kModular:jxl::FrameEncoding::kVarDCT)||header.loop_filter.gab||header.loop_filter.epf_iters||!metadata.m.xyb_encoded)return 8;
  printf("pub const bytes_%u=[_]u8{",id);for(auto b:bytes)printf("%u,",b);printf("};\n");
  for(unsigned floating=0;floating<3;++floating){
   auto* dec=JxlDecoderCreate(nullptr);JxlDecoderSubscribeEvents(dec,JXL_DEC_COLOR_ENCODING|JXL_DEC_FULL_IMAGE);JxlDecoderSetInput(dec,bytes.data(),bytes.size());JxlDecoderCloseInput(dec);std::vector<unsigned char> output(input.size()*(floating?4:1));unsigned frames=0;
   format.data_type=floating?JXL_TYPE_FLOAT:JXL_TYPE_UINT8;
   for(;;){auto status=JxlDecoderProcessInput(dec);if(status==JXL_DEC_SUCCESS)break;
    if(status==JXL_DEC_COLOR_ENCODING){JxlColorEncoding actual;if(JxlDecoderGetColorAsEncodedProfile(dec,JXL_COLOR_PROFILE_TARGET_DATA,&actual)!=JXL_DEC_SUCCESS||actual.transfer_function!=tfs[kind]||actual.color_space!=(gray?JXL_COLOR_SPACE_GRAY:JXL_COLOR_SPACE_RGB))return 9;if(floating==2){JxlColorEncoding linear;JxlColorEncodingSetToLinearSRGB(&linear,gray);if(JxlDecoderSetPreferredColorProfile(dec,&linear)!=JXL_DEC_SUCCESS)return 13;}}
    else if(status==JXL_DEC_NEED_IMAGE_OUT_BUFFER){if(JxlDecoderSetImageOutBuffer(dec,&format,output.data(),output.size())!=JXL_DEC_SUCCESS)return 10;}else if(status==JXL_DEC_FULL_IMAGE)++frames;else{fprintf(stderr,"id=%u status=%d\n",id,status);return 11;}}
   JxlDecoderDestroy(dec);if(frames!=1)return 12;
   if(floating==2&&kind==3){printf("pub const pq_scalar_%u=[_]u32{",id);for(size_t i=0;i<output.size();i+=4){float input;memcpy(&input,output.data()+i,4);float result=jxl::TF_PQ_Base::EncodedFromDisplay(info.intensity_target,input);uint32_t bits;memcpy(&bits,&result,4);printf("0x%08x,",bits);}printf("};\n");}
   printf("pub const %s_%u=[_]%s{",floating==2?"linear_bits":floating?"float_bits":"pixels",id,floating?"u32":"u8");for(size_t i=0;i<output.size();i+=floating?4:1){if(floating){uint32_t bits;memcpy(&bits,output.data()+i,4);printf("0x%08x,",bits);}else printf("%u,",output[i]);}printf("};\n");
  }
 }
}
