// Exercise upstream's actual render stage, including its SIMD approximations.
#include <cstdio>
#include <cstring>
#include <vector>
#include "lib/jxl/dec_xyb.h"
#include "lib/jxl/render_pipeline/stage_from_linear.h"
#include "lib/jxl/cms/transfer_functions.h"
int main(){
 printf("// Generated by tests/unit/transfer_stage_oracle.cc.\n");
 const jxl::TransferFunction tfs[]={jxl::TransferFunction::k709,jxl::TransferFunction::kLinear,jxl::TransferFunction::kSRGB,jxl::TransferFunction::kPQ,jxl::TransferFunction::kDCI,jxl::TransferFunction::kHLG,jxl::TransferFunction::kUnknown};
 const float samples[]={-2.f,-0.1f,-0.00001f,-0.f,0.f,0.0000001f,0.000009f,0.00001f,0.000011f,0.000099f,0.0001f,0.000101f,0.0001582588f,0.0002f,0.001f,0.0031308f,0.018f,0.083333333f,0.25f,0.5f,1.f,1.5f,2.f,8.f};
 printf("pub const inputs=[_]f32{");for(auto v:samples)printf("%.9e,",v);printf("};\n");
 for(unsigned id=0;id<28;++id){
  jxl::CodecMetadata metadata;metadata.m.color_encoding=jxl::ColorEncoding::SRGB();
  auto& tf=metadata.m.color_encoding.Tf();if(id%7==6){if(!tf.SetGamma(0.45))return 4;}else tf.SetTransferFunction(tfs[id%7]);
  metadata.m.tone_mapping.intensity_target=id/7==0?255:id/7==1?334:id/7==2?1000:10000;
  jxl::OutputEncodingInfo info;if(!info.SetFromMetadata(metadata))return 1;
  auto stage=jxl::GetFromLinearStage(info);if(!stage)return 2;
  const size_t count=sizeof(samples)/sizeof(samples[0]),offset=jxl::kRenderPipelineXOffset;
  std::vector<std::vector<float>> storage(3,std::vector<float>(offset+count+128,0));
  jxl::RenderPipelineStage::RowInfo rows(3);
  for(unsigned c=0;c<3;++c){for(size_t x=0;x<count;++x)storage[c][offset+x]=samples[x]*(c==0?1.f:c==1?0.5f:0.25f);rows[c].push_back(storage[c].data());}
  if(!stage->ProcessRow(rows,{},0,count,0,0,0))return 3;
  if(id%7==3){printf("pub const scalar_%u=[_][3]u32{",id);for(float sample:samples){printf(".{");for(unsigned c=0;c<3;++c){float result=jxl::TF_PQ_Base::EncodedFromDisplay(info.orig_intensity_target,sample*(c==0?1.f:c==1?0.5f:0.25f));uint32_t bits;memcpy(&bits,&result,4);printf("0x%08x,",bits);}printf("},");}printf("};\n");}
  printf("pub const output_%u=[_][3]u32{",id);for(size_t x=0;x<count;++x){printf(".{");for(unsigned c=0;c<3;++c){uint32_t bits;memcpy(&bits,&storage[c][offset+x],4);printf("0x%08x,",bits);}printf("},");}printf("};\n");
 }
}
