// Pixel comparisons use the actual upstream upsampling stage.
#include <cmath>
#include <cstdio>
#include "lib/jxl/image_ops.h"
#include "lib/jxl/memory_manager_internal.h"
#include "lib/jxl/image_metadata.h"
#include "lib/jxl/render_pipeline/stage_upsampling.h"
struct StageAccess: jxl::RenderPipelineStage {using jxl::RenderPipelineStage::PrepareForThreads;};
jxl::Status Generate(JxlMemoryManager* memory,size_t id){
 const size_t width=id==0?1:id==1?7:13,height=id==0?3:id==1?5:9,pad=jxl::kRenderPipelineXOffset;
 JXL_ASSIGN_OR_RETURN(jxl::ImageF input,jxl::ImageF::Create(memory,width+2*pad,height+4));
 for(size_t y=0;y<height+4;++y)for(size_t x=0;x<width+2*pad;++x){const size_t mx=jxl::Mirror(static_cast<int64_t>(x)-pad,width),my=jxl::Mirror(static_cast<int64_t>(y)-2,height);input.Row(y)[x]=(static_cast<int>((mx*13+my*17)%37)-18)/256.f;}
 printf("pub const input_%zu=[_]i32{",id);for(size_t y=0;y<height;++y)for(size_t x=0;x<width;++x)printf("%d,",static_cast<int>(input.Row(y+2)[x+pad]*256));printf("};\n");
 for(size_t shift=1;shift<=3;++shift){const size_t factor=1<<shift;
  jxl::CustomTransformData params;
  if(id==3){float* weights=shift==1?params.upsampling2_weights:shift==2?params.upsampling4_weights:params.upsampling8_weights;size_t count=shift==1?15:shift==2?55:210;for(size_t i=0;i<count;++i)weights[i]=(static_cast<int>(i%7)-3)/64.f;}
  auto stage=jxl::GetUpsamplingStage(memory,params,0,shift);JXL_RETURN_IF_ERROR((stage.get()->*&StageAccess::PrepareForThreads)(1));
  JXL_ASSIGN_OR_RETURN(jxl::ImageF output,jxl::ImageF::Create(memory,width*factor+2*pad,height*factor));
  for(size_t y=0;y<height;++y){jxl::RenderPipelineStage::RowInfo rows(1),out(1);for(size_t dy=0;dy<5;++dy)rows[0].push_back(input.Row(y+dy));for(size_t dy=0;dy<factor;++dy)out[0].push_back(output.Row(y*factor+dy));JXL_RETURN_IF_ERROR(stage->ProcessRow(rows,out,0,width,0,y,0));}
  printf("pub const output_%zu_%zu=[_]i32{",id,factor);for(size_t y=0;y<height*factor;++y)for(size_t x=0;x<width*factor;++x)printf("%d,",static_cast<int>(std::llround(output.Row(y)[x+pad]*(1<<24))));printf("};\n");
 }
 return true;
}
int main(){JxlMemoryManager memory;if(!jxl::MemoryManagerInit(&memory,nullptr))return 1;printf("// Generated by tests/unit/upsampling_oracle.cc. Input 2^8; output 2^24.\n");for(size_t id=0;id<4;++id)if(!Generate(&memory,id))return 2;}
