// Lossy fixtures and decoded RGB samples from the retained upstream public API.
#include <cstdio>
#include <vector>
#include "jxl/encode.h"
#include "jxl/decode.h"
#include "jxl/color_encoding.h"
#include "lib/jxl/enc_fields.h"
#include "lib/jxl/dec_bit_reader.h"
#include "lib/jxl/memory_manager_internal.h"
jxl::Status Rewrite(std::vector<unsigned char>* compressed,unsigned id){
 JxlMemoryManager memory;JXL_RETURN_IF_ERROR(jxl::MemoryManagerInit(&memory,nullptr));
 jxl::BitReader reader(*compressed);if(reader.ReadBits(16)!=0x0aff)return false;
 jxl::CodecMetadata metadata;
 JXL_RETURN_IF_ERROR(jxl::ReadSizeHeader(&reader,&metadata.size));
 JXL_RETURN_IF_ERROR(jxl::ReadImageMetadata(&reader,&metadata.m));
 metadata.transform_data.nonserialized_xyb_encoded=metadata.m.xyb_encoded;
 JXL_RETURN_IF_ERROR(jxl::Bundle::Read(&reader,&metadata.transform_data));
 JXL_RETURN_IF_ERROR(reader.JumpToByteBoundary());const size_t offset=reader.TotalBitsConsumed()/8;JXL_RETURN_IF_ERROR(reader.Close());
 auto& opsin=metadata.transform_data.opsin_inverse_matrix;
 if(id==0){opsin.quant_biases[0]=0.5f;opsin.quant_biases[1]=0.75f;opsin.quant_biases[2]=0.625f;opsin.quant_biases[3]=0.25f;}
 if(id==1){for(auto& row:opsin.inverse_matrix)for(auto& value:row)value*=0.75f;opsin.opsin_biases[0]=-0.0078125f;}
 if(id==2){for(auto& row:opsin.inverse_matrix)for(auto& value:row)value=0;for(auto& value:opsin.opsin_biases)value=0;for(auto& value:opsin.quant_biases)value=0;}
 jxl::BitWriter writer(&memory);JXL_RETURN_IF_ERROR(jxl::WriteCodestreamHeaders(&metadata,&writer,nullptr));writer.ZeroPadToByte();
 auto header=writer.GetSpan();std::vector<unsigned char> result(header.begin(),header.end());result.insert(result.end(),compressed->begin()+offset,compressed->end());*compressed=std::move(result);return true;
}

int main() {
	printf("// Generated by tests/unit/vardct_opsin_oracle.cc with upstream libjxl.\n");
	for (unsigned id=0;id<3;++id) {
		const unsigned width=19;
		const unsigned height=13;
		std::vector<unsigned char> pixels(width*height*3);
		for(unsigned y=0;y<height;++y)for(unsigned x=0;x<width;++x){
			pixels[(y*width+x)*3]=(x*13+y*3)%256;
			pixels[(y*width+x)*3+1]=(x*2+y*17)%256;
			pixels[(y*width+x)*3+2]=(x*7+y*11)%256;
		}
		JxlEncoder* encoder=JxlEncoderCreate(nullptr);
		JxlBasicInfo info; JxlEncoderInitBasicInfo(&info);
		info.xsize=width;info.ysize=height;info.num_color_channels=3;info.bits_per_sample=8;info.uses_original_profile=JXL_FALSE;
		if(JxlEncoderSetBasicInfo(encoder,&info)!=JXL_ENC_SUCCESS)return 1;
		JxlColorEncoding color;JxlColorEncodingSetToSRGB(&color,JXL_FALSE);
		if(JxlEncoderSetColorEncoding(encoder,&color)!=JXL_ENC_SUCCESS)return 2;
		auto* settings=JxlEncoderFrameSettingsCreate(encoder,nullptr);
		if(JxlEncoderSetFrameDistance(settings,1.0f)!=JXL_ENC_SUCCESS)return 3;
		for(auto option:{JXL_ENC_FRAME_SETTING_EPF,JXL_ENC_FRAME_SETTING_GABORISH,JXL_ENC_FRAME_SETTING_PATCHES,JXL_ENC_FRAME_SETTING_NOISE,JXL_ENC_FRAME_SETTING_MODULAR})
			if(JxlEncoderFrameSettingsSetOption(settings,option,0)!=JXL_ENC_SUCCESS)return 4;
		if(JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_EFFORT,5)!=JXL_ENC_SUCCESS)return 5;
		if(id==5&&JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_PROGRESSIVE_AC,1)!=JXL_ENC_SUCCESS)return 10;
		if(id>=6){
			if(JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_GABORISH,id==7?0:1)!=JXL_ENC_SUCCESS)return 11;
			if(JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_EPF,id==6?0:id-6)!=JXL_ENC_SUCCESS)return 12;
		}
		JxlPixelFormat format={3,JXL_TYPE_UINT8,JXL_NATIVE_ENDIAN,0};
		if(JxlEncoderAddImageFrame(settings,&format,pixels.data(),pixels.size())!=JXL_ENC_SUCCESS)return 6;
		JxlEncoderCloseInput(encoder);
		std::vector<unsigned char> compressed(1<<20);auto* next=compressed.data();size_t avail=compressed.size();
		if(JxlEncoderProcessOutput(encoder,&next,&avail)!=JXL_ENC_SUCCESS)return 7;
		compressed.resize(compressed.size()-avail);JxlEncoderDestroy(encoder);
 if(!Rewrite(&compressed,id))return 13;
		JxlDecoder* decoder=JxlDecoderCreate(nullptr);
		JxlDecoderSubscribeEvents(decoder,JXL_DEC_BASIC_INFO|JXL_DEC_FULL_IMAGE);
		JxlDecoderSetInput(decoder,compressed.data(),compressed.size());JxlDecoderCloseInput(decoder);
		std::vector<unsigned char> output(pixels.size());
		for(;;){auto status=JxlDecoderProcessInput(decoder);if(status==JXL_DEC_SUCCESS)break;
			if(status==JXL_DEC_NEED_IMAGE_OUT_BUFFER){if(JxlDecoderSetImageOutBuffer(decoder,&format,output.data(),output.size())!=JXL_DEC_SUCCESS)return 8;}
			else if(status!=JXL_DEC_BASIC_INFO&&status!=JXL_DEC_FULL_IMAGE)return 9;
		}
		JxlDecoderDestroy(decoder);
		printf("pub const bytes_%u = [_]u8{",id);for(auto byte:compressed)printf("0x%02x,",byte);printf("};\n");
		printf("pub const rgb_%u = [_]u8{",id);for(auto byte:output)printf("%u,",byte);printf("};\n");
	}
}
