// Lossy fixtures and decoded RGB samples from the retained upstream public API.
#include <cstdio>
#include <vector>
#include "jxl/encode.h"
#include "jxl/decode.h"
#include "jxl/color_encoding.h"
int main() {
	printf("// Generated by tests/unit/vardct_frame_oracle.cc with upstream libjxl.\n");
	for (unsigned id=0;id<6;++id) {
		const unsigned width=id==0?8:id==1?19:id==3?272:id==4?2056:40;
		const unsigned height=id==0||id==4?8:id==1?13:id==3?19:32;
		std::vector<unsigned char> pixels(width*height*3);
		for(unsigned y=0;y<height;++y)for(unsigned x=0;x<width;++x){
			pixels[(y*width+x)*3]=(x*13+y*3)%256;
			pixels[(y*width+x)*3+1]=(x*2+y*17)%256;
			pixels[(y*width+x)*3+2]=(x*7+y*11)%256;
		}
		JxlEncoder* encoder=JxlEncoderCreate(nullptr);
		JxlBasicInfo info; JxlEncoderInitBasicInfo(&info);
		info.xsize=width;info.ysize=height;info.num_color_channels=3;info.bits_per_sample=8;info.uses_original_profile=JXL_FALSE;
		if(JxlEncoderSetBasicInfo(encoder,&info)!=JXL_ENC_SUCCESS)return 1;
		JxlColorEncoding color;JxlColorEncodingSetToSRGB(&color,JXL_FALSE);
		if(JxlEncoderSetColorEncoding(encoder,&color)!=JXL_ENC_SUCCESS)return 2;
		auto* settings=JxlEncoderFrameSettingsCreate(encoder,nullptr);
		if(JxlEncoderSetFrameDistance(settings,1.0f)!=JXL_ENC_SUCCESS)return 3;
		for(auto option:{JXL_ENC_FRAME_SETTING_EPF,JXL_ENC_FRAME_SETTING_GABORISH,JXL_ENC_FRAME_SETTING_PATCHES,JXL_ENC_FRAME_SETTING_NOISE,JXL_ENC_FRAME_SETTING_MODULAR})
			if(JxlEncoderFrameSettingsSetOption(settings,option,0)!=JXL_ENC_SUCCESS)return 4;
		if(JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_EFFORT,5)!=JXL_ENC_SUCCESS)return 5;
		if(id==5&&JxlEncoderFrameSettingsSetOption(settings,JXL_ENC_FRAME_SETTING_PROGRESSIVE_AC,1)!=JXL_ENC_SUCCESS)return 10;
		JxlPixelFormat format={3,JXL_TYPE_UINT8,JXL_NATIVE_ENDIAN,0};
		if(JxlEncoderAddImageFrame(settings,&format,pixels.data(),pixels.size())!=JXL_ENC_SUCCESS)return 6;
		JxlEncoderCloseInput(encoder);
		std::vector<unsigned char> compressed(1<<20);auto* next=compressed.data();size_t avail=compressed.size();
		if(JxlEncoderProcessOutput(encoder,&next,&avail)!=JXL_ENC_SUCCESS)return 7;
		compressed.resize(compressed.size()-avail);JxlEncoderDestroy(encoder);
		JxlDecoder* decoder=JxlDecoderCreate(nullptr);
		JxlDecoderSubscribeEvents(decoder,JXL_DEC_BASIC_INFO|JXL_DEC_FULL_IMAGE);
		JxlDecoderSetInput(decoder,compressed.data(),compressed.size());JxlDecoderCloseInput(decoder);
		std::vector<unsigned char> output(pixels.size());
		for(;;){auto status=JxlDecoderProcessInput(decoder);if(status==JXL_DEC_SUCCESS)break;
			if(status==JXL_DEC_NEED_IMAGE_OUT_BUFFER){if(JxlDecoderSetImageOutBuffer(decoder,&format,output.data(),output.size())!=JXL_DEC_SUCCESS)return 8;}
			else if(status!=JXL_DEC_BASIC_INFO&&status!=JXL_DEC_FULL_IMAGE)return 9;
		}
		JxlDecoderDestroy(decoder);
		printf("pub const bytes_%u = [_]u8{",id);for(auto byte:compressed)printf("0x%02x,",byte);printf("};\n");
		printf("pub const rgb_%u = [_]u8{",id);for(auto byte:output)printf("%u,",byte);printf("};\n");
	}
}
