// Wide signed samples and wrapping predictor error state from upstream.
#include <cstdio>
#include <cstdint>
#include <cstring>
#include "lib/jxl/modular/encoding/context_predict.h"
int main(){
 const uint32_t words[]={0,0x7fffffff,0x80000000,0xffffffff,0x3f800000,0xbf800000,0x3f000000,0xbf000000,0x7f800000,0xff800000,0x7fc00001,0xffc00001,0x12345678,0x87654321,0x40000000,0xc0000000};
 int32_t pixels[64];for(unsigned i=0;i<64;++i){const auto word=words[(i*5+i/16)%16];memcpy(pixels+i,&word,4);}
 printf("// Generated by tests/unit/weighted_wide_oracle.cc.\npub const pixels=[_]i32{");for(auto p:pixels)printf("%d,",p);printf("};\npub const state=[_][6]i64{\n");
 jxl::weighted::Header header;jxl::weighted::State state(header,16,4);
 for(unsigned y=0;y<4;++y)for(unsigned x=0;x<16;++x){
  const int64_t n=y?pixels[(y-1)*16+x]:0,w=x?pixels[y*16+x-1]:n,ne=y?pixels[(y-1)*16+std::min(x+1,15u)]:0,nw=y&&x?pixels[(y-1)*16+x-1]:n,nn=y>1?pixels[(y-2)*16+x]:n;
  const int64_t pred=state.Predict<false>(x,y,16,n,w,ne,nw,nn,nullptr,0);state.UpdateErrors(pixels[y*16+x],x,y,16);
  const unsigned index=(y&1?0:18)+x;printf(".{%lld,%d",(long long)pred,state.error[index]);for(unsigned p=0;p<4;++p)printf(",%u",state.pred_errors[p][index]);printf("},\n");
 }
 printf("};\n");
}
