// Call upstream property computation over signed 32-bit extrema.
#include <cstdio>
#include <cstdint>
#include "lib/jxl/modular/transform/transform.h"
#include "lib/jxl/modular/encoding/context_predict.h"
#include "lib/jxl/memory_manager_internal.h"
static jxl::Status Generate(JxlMemoryManager* memory) {
 constexpr unsigned w=7,h=4;
 const int32_t samples[]={INT32_MIN,INT32_MAX,0,-1,1,0x40000000,-0x40000000};
 JXL_ASSIGN_OR_RETURN(jxl::Image image,jxl::Image::Create(memory,w,h,32,2));
 for(unsigned c=0;c<2;++c)for(unsigned y=0;y<h;++y)for(unsigned x=0;x<w;++x)
  image.channel[c].Row(y)[x]=samples[(x*(y+1)+y*3+c*2)%7];
 puts("// Generated by tests/unit/wide_property_oracle.cc using upstream Predict and PrecomputeReferences.");
 for(unsigned c=0;c<2;++c){printf("pub const samples_%u=[_]i32{",c);for(unsigned y=0;y<h;++y)for(unsigned x=0;x<w;++x)printf("%d,",image.channel[c].Row(y)[x]);puts("};");}
 JXL_ASSIGN_OR_RETURN(jxl::Channel references,jxl::Channel::Create(memory,4,w));
 jxl::Properties props(20);const auto& ch=image.channel[1];
 puts("pub const properties=[_][20]i32{");
 for(unsigned y=0;y<h;++y){jxl::InitPropsRow(&props,{{1,0}},y);jxl::PrecomputeReferences(ch,y,image,1,&references);
  for(unsigned x=0;x<w;++x){
   jxl::detail::Predict<jxl::detail::kForceComputeProperties>(&props,w,ch.Row(y)+x,ch.plane.PixelsPerRow(),x,y,jxl::Predictor::Zero,nullptr,&references,nullptr,nullptr);
   printf(".{");for(auto p:props)printf("%d,",p);puts("},");
  }
 }
 puts("};");return true;
}
int main(){JxlMemoryManager memory;if(!jxl::MemoryManagerInit(&memory,nullptr))return 1;return Generate(&memory)?0:2;}
